Run: 56
/cm/local/apps/slurm/var/spool/job988497/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
starting loops
../data/r/1213/1213.pkl
working on 
../data/r/1213/reg_full_MAR_0.5_3
3.1197445392608643
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-10-04 19:59:06,373] A new study created in memory with name: no-name-6fae70b9-3f68-4142-b85d-e906938ad24d
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-10-04 19:59:07,200] Trial 12 finished with value: 0.45635018704939584 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 12 with value: 0.45635018704939584.
running
[I 2024-10-04 19:59:07,709] Trial 5 finished with value: 0.292634309674553 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 5 with value: 0.292634309674553.
running
[I 2024-10-04 19:59:09,882] Trial 0 finished with value: 0.3784595419050992 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 5 with value: 0.292634309674553.
running
[I 2024-10-04 19:59:10,807] Trial 2 finished with value: 0.4402999346775601 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 5 with value: 0.292634309674553.
running
[I 2024-10-04 19:59:20,811] Trial 11 finished with value: 0.27423676877995923 and parameters: {'model_name': 'VAE', 'batch_size': 32, 'iterations': 1, 'learning_rate': 0.00100758566821908, 'p_miss': 0.11877723821105989}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 19:59:21,691] Trial 20 finished with value: 0.45635018704939584 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 19:59:26,226] Trial 19 finished with value: 0.2751663546426853 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 4, 'learning_rate': 0.00035288503064090853, 'p_miss': 0.029646940902689843}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 19:59:27,326] Trial 22 finished with value: 0.3784595419050992 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 19:59:30,542] Trial 3 finished with value: 0.445616479426886 and parameters: {'model_name': 'GAIN', 'batch_size': 6, 'hint_rate': 0.22062131275059307, 'alpha': 61, 'iterations': 7, 'learning_rate': 0.0006715611850604244, 'p_miss': 0.16116836673946963}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 19:59:45,573] Trial 21 finished with value: 0.44895451985662105 and parameters: {'model_name': 'GAIN', 'batch_size': 235, 'hint_rate': 0.6797290946163378, 'alpha': 44, 'iterations': 23, 'learning_rate': 0.026464080378305995, 'p_miss': 0.21462535209881442}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:16,806] Trial 23 finished with value: 0.28182062777562367 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:21,094] Trial 26 finished with value: 0.27961855603948016 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 1, 'learning_rate': 0.00011068930357162885, 'p_miss': 0.012649887042911059}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:24,524] Trial 14 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 5, 'hint_rate': 0.19070846083102172, 'alpha': 20, 'iterations': 602, 'learning_rate': 0.0799795821550844, 'p_miss': 0.07796141934404478}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:27,291] Trial 8 finished with value: 0.28482999748986393 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 13044, 'weights': 'uniform'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:30,260] Trial 28 finished with value: 0.28044318324718237 and parameters: {'model_name': 'VAE', 'batch_size': 93, 'iterations': 1, 'learning_rate': 0.0009412927007285849, 'p_miss': 0.08852914910247897}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:31,781] Trial 9 finished with value: 0.292634309674553 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 56035, 'weights': 'uniform'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:32,263] Trial 29 finished with value: 0.278718564407067 and parameters: {'model_name': 'VAE', 'batch_size': 93, 'iterations': 1, 'learning_rate': 0.0011820120337740346, 'p_miss': 0.08108189672707478}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:43,574] Trial 31 finished with value: 0.279553842417924 and parameters: {'model_name': 'VAE', 'batch_size': 32, 'iterations': 5, 'learning_rate': 0.0003363697132984151, 'p_miss': 0.028162720901242944}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:44,837] Trial 18 finished with value: 0.29043743274195954 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 40449, 'weights': 'uniform'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:52,219] Trial 24 finished with value: 0.292634309674553 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 55288, 'weights': 'uniform'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:53,301] Trial 16 finished with value: 0.2864374001104215 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 29422, 'weights': 'distance'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:56,465] Trial 6 finished with value: 0.28759138810049034 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 36633, 'weights': 'distance'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:00:57,561] Trial 13 finished with value: 0.2879501947509542 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 38752, 'weights': 'distance'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:01:05,000] Trial 37 finished with value: 0.27734601518153246 and parameters: {'model_name': 'VAE', 'batch_size': 45, 'iterations': 1, 'learning_rate': 0.0024025404852403556, 'p_miss': 0.10232003728342569}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:01:05,728] Trial 38 finished with value: 0.27829820954458445 and parameters: {'model_name': 'VAE', 'batch_size': 37, 'iterations': 1, 'learning_rate': 0.004287744559205295, 'p_miss': 0.10500439970648448}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:01:06,718] Trial 10 finished with value: 0.3098691066842892 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 1, 'imputation_order': 'descending'}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:01:13,701] Trial 36 finished with value: 0.27667123042993425 and parameters: {'model_name': 'VAE', 'batch_size': 802, 'iterations': 1, 'learning_rate': 0.002390310341139018, 'p_miss': 0.106118008395626}. Best is trial 11 with value: 0.27423676877995923.
running
[I 2024-10-04 20:01:25,427] Trial 39 finished with value: 0.2741928918702602 and parameters: {'model_name': 'VAE', 'batch_size': 17, 'iterations': 4, 'learning_rate': 0.004610524568064692, 'p_miss': 0.14837351639805113}. Best is trial 39 with value: 0.2741928918702602.
running
[I 2024-10-04 20:02:48,783] Trial 7 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.9252168193926231, 'alpha': 1, 'iterations': 1141, 'learning_rate': 0.0017992698526888484, 'p_miss': 0.25491480029317887}. Best is trial 39 with value: 0.2741928918702602.
running
[I 2024-10-04 20:03:19,383] Trial 44 finished with value: 0.2711054212028755 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 9, 'learning_rate': 0.009201337858621279, 'p_miss': 0.17442172769792816}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:06:12,400] Trial 35 finished with value: 0.3236870454604034 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 85, 'learning_rate': 0.006433091724246561, 'p_miss': 0.2909875136353137}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:06:47,988] Trial 46 finished with value: 0.2723487538317049 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 8, 'learning_rate': 0.009528040235735134, 'p_miss': 0.1665264461790714}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:07:30,896] Trial 45 finished with value: 0.30030388614773484 and parameters: {'model_name': 'VAE', 'batch_size': 9, 'iterations': 77, 'learning_rate': 0.009550064276491705, 'p_miss': 0.16758860652343913}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:07:58,833] Trial 32 finished with value: 0.27273687227152976 and parameters: {'model_name': 'VAE', 'batch_size': 19, 'iterations': 118, 'learning_rate': 0.00015001095885849188, 'p_miss': 0.27528429706218055}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:07:59,093] Trial 43 finished with value: 0.2998567301996245 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 123, 'learning_rate': 0.008251929172351832, 'p_miss': 0.17846422987213062}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:08,252] Trial 47 finished with value: 0.2934798133536069 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 22, 'learning_rate': 0.010734523762978631, 'p_miss': 0.170768864547394}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:16,218] Trial 34 finished with value: 0.3343815698833119 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 154, 'learning_rate': 0.003676528871733868, 'p_miss': 0.2978192733306467}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:22,902] Trial 48 finished with value: 0.2980362691877473 and parameters: {'model_name': 'VAE', 'batch_size': 11, 'iterations': 18, 'learning_rate': 0.01396060862725044, 'p_miss': 0.19252945118681605}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:37,442] Trial 50 finished with value: 0.3004087188476866 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 19, 'learning_rate': 0.01716085322993536, 'p_miss': 0.20330661062502287}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:41,773] Trial 49 finished with value: 0.2982945823934188 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 24, 'learning_rate': 0.014381964120717539, 'p_miss': 0.2014487854923001}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:08:45,557] Trial 52 finished with value: 0.2981668707326496 and parameters: {'model_name': 'VAE', 'batch_size': 15, 'iterations': 18, 'learning_rate': 0.020262464552267285, 'p_miss': 0.2085269195840766}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:09,852] Trial 15 finished with value: 0.3005716342533242 and parameters: {'model_name': 'VAE', 'batch_size': 4, 'iterations': 241, 'learning_rate': 0.004682148451345704, 'p_miss': 0.021561381536567746}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:27,868] Trial 53 finished with value: 0.28174509892592775 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 10, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:33,490] Trial 54 finished with value: 0.2817450951341058 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 10, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:35,656] Trial 58 finished with value: 0.44432465115451214 and parameters: {'model_name': 'GAIN', 'batch_size': 21, 'hint_rate': 0.5095856173800027, 'alpha': 100, 'iterations': 3, 'learning_rate': 0.00012572526874886532, 'p_miss': 0.1367045712511933}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:39,156] Trial 59 finished with value: 0.4456490054994105 and parameters: {'model_name': 'GAIN', 'batch_size': 20, 'hint_rate': 0.5194568807648112, 'alpha': 92, 'iterations': 3, 'learning_rate': 0.00013895084077221448, 'p_miss': 0.13260216640758593}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:40,304] Trial 41 finished with value: 0.29634532455213136 and parameters: {'model_name': 'VAE', 'batch_size': 787, 'iterations': 101, 'learning_rate': 0.004059132973820808, 'p_miss': 0.1553296713797045}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:48,452] Trial 60 finished with value: 0.3015772255217356 and parameters: {'model_name': 'VAE', 'batch_size': 22, 'iterations': 8, 'learning_rate': 0.03067939474509235, 'p_miss': 0.13761533006683585}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:48,641] Trial 61 finished with value: 0.28798704847095824 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 8, 'learning_rate': 0.03226956753878327, 'p_miss': 0.12967188404181798}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:49,516] Trial 64 finished with value: 0.292634309674553 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:50,282] Trial 63 finished with value: 0.4402999346775601 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:52,732] Trial 62 finished with value: 0.3101091719105868 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 9, 'learning_rate': 0.04375497603562815, 'p_miss': 0.13724055622342657}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:55,703] Trial 65 finished with value: 0.2753037499312837 and parameters: {'model_name': 'VAE', 'batch_size': 80, 'iterations': 2, 'learning_rate': 0.0003858066503220702, 'p_miss': 0.2525296514081094}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:09:57,896] Trial 66 finished with value: 0.2752852686084397 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 3, 'learning_rate': 0.00030910630342030946, 'p_miss': 0.05543443916460021}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:10:00,135] Trial 67 finished with value: 0.2727119492907472 and parameters: {'model_name': 'VAE', 'batch_size': 64, 'iterations': 3, 'learning_rate': 0.00038400628075481214, 'p_miss': 0.056181705801617604}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:10:02,679] Trial 68 finished with value: 0.2770901010724188 and parameters: {'model_name': 'VAE', 'batch_size': 54, 'iterations': 3, 'learning_rate': 0.00024517408052405863, 'p_miss': 0.05718761454879068}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:10:21,545] Trial 51 finished with value: 0.38276763726048774 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 10, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 44 with value: 0.2711054212028755.
running
[I 2024-10-04 20:11:09,207] Trial 70 finished with value: 0.27056948169279316 and parameters: {'model_name': 'VAE', 'batch_size': 59, 'iterations': 43, 'learning_rate': 0.0006294931254618245, 'p_miss': 0.05241551409543516}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:11:15,456] Trial 69 finished with value: 0.2733137686719882 and parameters: {'model_name': 'VAE', 'batch_size': 48, 'iterations': 47, 'learning_rate': 0.00019645165599741876, 'p_miss': 0.2375704146930684}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:11:15,626] Trial 72 finished with value: 0.28353678903273016 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6811, 'weights': 'distance'}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:11:56,876] Trial 73 finished with value: 0.2815717198131741 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1099, 'weights': 'distance'}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:12:05,378] Trial 74 finished with value: 0.2827417793746669 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3440, 'weights': 'distance'}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:12:51,692] Trial 33 finished with value: 0.2957835708748956 and parameters: {'model_name': 'VAE', 'batch_size': 935, 'iterations': 135, 'learning_rate': 0.009063178686377968, 'p_miss': 0.2588411480402619}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:13:14,389] Trial 75 finished with value: 0.27654991571977033 and parameters: {'model_name': 'VAE', 'batch_size': 279, 'iterations': 39, 'learning_rate': 0.0001936407336089502, 'p_miss': 0.23532801455461874}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:14:13,548] Trial 76 finished with value: 0.27783743228578667 and parameters: {'model_name': 'VAE', 'batch_size': 172, 'iterations': 48, 'learning_rate': 0.00019527068506284864, 'p_miss': 0.241326519310273}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:14:48,385] Trial 80 finished with value: 0.2771506253804654 and parameters: {'model_name': 'VAE', 'batch_size': 62, 'iterations': 11, 'learning_rate': 0.0005298744137275828, 'p_miss': 0.2802352572035636}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:15:13,827] Trial 78 finished with value: 0.27426300200048387 and parameters: {'model_name': 'VAE', 'batch_size': 155, 'iterations': 44, 'learning_rate': 0.0001903946074590802, 'p_miss': 0.23456197436843515}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:17:49,802] Trial 40 finished with value: 0.29624604901512847 and parameters: {'model_name': 'VAE', 'batch_size': 958, 'iterations': 217, 'learning_rate': 0.003511486631716792, 'p_miss': 0.14092877812844437}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:19:01,878] Trial 4 finished with value: 0.456678175832563 and parameters: {'model_name': 'GAIN', 'batch_size': 50, 'hint_rate': 0.44597261013059264, 'alpha': 83, 'iterations': 1076, 'learning_rate': 0.0007595630035106476, 'p_miss': 0.20901530687372386}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:21:43,599] Trial 83 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 15, 'hint_rate': 0.9753053964457615, 'alpha': 66, 'iterations': 523, 'learning_rate': 0.0005809942991432739, 'p_miss': 0.05010950915093919}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:33:08,228] Trial 81 finished with value: 0.2936416072357984 and parameters: {'model_name': 'VAE', 'batch_size': 15, 'iterations': 397, 'learning_rate': 0.0006532884405236668, 'p_miss': 0.05592291041307175}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:34:26,605] Trial 82 finished with value: 0.29725039690091515 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 419, 'learning_rate': 0.005773147845218526, 'p_miss': 0.05498375647045297}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:39:38,642] Trial 84 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 15, 'hint_rate': 0.028273928801975046, 'alpha': 45, 'iterations': 5212, 'learning_rate': 0.005565045018603669, 'p_miss': 0.04967471156245798}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:39:56,815] Trial 88 finished with value: 0.2787718485412144 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 5, 'learning_rate': 0.00044611519768181983, 'p_miss': 0.18589416707363374}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:40:04,706] Trial 89 finished with value: 0.27996146265803573 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 2, 'learning_rate': 0.0012783803804063693, 'p_miss': 0.12152181169073328}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:40:13,768] Trial 90 finished with value: 0.27746372784080603 and parameters: {'model_name': 'VAE', 'batch_size': 28, 'iterations': 2, 'learning_rate': 0.0011086295932807696, 'p_miss': 0.26827750943027684}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:40:48,017] Trial 91 finished with value: 0.28255731467326883 and parameters: {'model_name': 'VAE', 'batch_size': 72, 'iterations': 12, 'learning_rate': 0.00028079587208259334, 'p_miss': 0.07008993959037882}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:41:03,668] Trial 92 finished with value: 0.27519063545509254 and parameters: {'model_name': 'VAE', 'batch_size': 40, 'iterations': 5, 'learning_rate': 0.0017894743450812876, 'p_miss': 0.14938782443046308}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:41:05,388] Trial 93 finished with value: 0.4402999346775601 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 70 with value: 0.27056948169279316.
running
[I 2024-10-04 20:43:53,980] Trial 94 finished with value: 0.2670577963286633 and parameters: {'model_name': 'VAE', 'batch_size': 122, 'iterations': 59, 'learning_rate': 0.0008653051043608123, 'p_miss': 0.2180905494473802}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:46:14,711] Trial 95 finished with value: 0.2721068931207443 and parameters: {'model_name': 'VAE', 'batch_size': 112, 'iterations': 35, 'learning_rate': 0.0008930343641905069, 'p_miss': 0.03468355792327567}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:49:26,055] Trial 96 finished with value: 0.27451064217830934 and parameters: {'model_name': 'VAE', 'batch_size': 125, 'iterations': 59, 'learning_rate': 0.000858219668367731, 'p_miss': 0.03619563704146746}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:50:51,354] Trial 97 finished with value: 0.2706422955946164 and parameters: {'model_name': 'VAE', 'batch_size': 128, 'iterations': 30, 'learning_rate': 0.0008098750083231155, 'p_miss': 0.22592301529926512}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:52:20,854] Trial 98 finished with value: 0.2745240969682644 and parameters: {'model_name': 'VAE', 'batch_size': 117, 'iterations': 29, 'learning_rate': 0.000784584710321237, 'p_miss': 0.21954448329705906}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:54:28,048] Trial 99 finished with value: 0.27146792540400166 and parameters: {'model_name': 'VAE', 'batch_size': 319, 'iterations': 32, 'learning_rate': 0.0016224348605811821, 'p_miss': 0.2260764084689606}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 20:56:27,751] Trial 100 finished with value: 0.2742618297813718 and parameters: {'model_name': 'VAE', 'batch_size': 379, 'iterations': 32, 'learning_rate': 0.0019815511445801064, 'p_miss': 0.012416708666241269}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:15:41,025] Trial 79 finished with value: 0.2953162798477567 and parameters: {'model_name': 'VAE', 'batch_size': 60, 'iterations': 3380, 'learning_rate': 0.0004376622127869307, 'p_miss': 0.2782530762343956}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:18:01,488] Trial 71 finished with value: 0.31309579748651 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'ascending'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:18:45,027] Trial 103 finished with value: 0.27028397154444217 and parameters: {'model_name': 'VAE', 'batch_size': 370, 'iterations': 13, 'learning_rate': 0.0012670355318140192, 'p_miss': 0.2235578657086245}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:19:44,570] Trial 104 finished with value: 0.27209312333887586 and parameters: {'model_name': 'VAE', 'batch_size': 513, 'iterations': 14, 'learning_rate': 0.0014907198342441047, 'p_miss': 0.22214244238354408}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:21:13,240] Trial 105 finished with value: 0.2706933669276804 and parameters: {'model_name': 'VAE', 'batch_size': 473, 'iterations': 15, 'learning_rate': 0.0014830399975365597, 'p_miss': 0.22484142796709208}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:22:18,101] Trial 106 finished with value: 0.27148660017879084 and parameters: {'model_name': 'VAE', 'batch_size': 510, 'iterations': 13, 'learning_rate': 0.0015640348870658693, 'p_miss': 0.2218744741243968}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:23:09,924] Trial 107 finished with value: 0.27331140875655324 and parameters: {'model_name': 'VAE', 'batch_size': 515, 'iterations': 13, 'learning_rate': 0.0014558479918791941, 'p_miss': 0.22059752953157544}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:24:47,717] Trial 108 finished with value: 0.27871988069700326 and parameters: {'model_name': 'VAE', 'batch_size': 539, 'iterations': 16, 'learning_rate': 0.002894756785145943, 'p_miss': 0.22624014122268876}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:26:34,194] Trial 109 finished with value: 0.2700821037048152 and parameters: {'model_name': 'VAE', 'batch_size': 310, 'iterations': 29, 'learning_rate': 0.0016085058958464056, 'p_miss': 0.2124862988809061}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:30:15,373] Trial 110 finished with value: 0.28606412484692134 and parameters: {'model_name': 'VAE', 'batch_size': 306, 'iterations': 68, 'learning_rate': 0.0015854376176993345, 'p_miss': 0.24709998111279918}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:32:07,412] Trial 111 finished with value: 0.275342597537883 and parameters: {'model_name': 'VAE', 'batch_size': 492, 'iterations': 25, 'learning_rate': 0.0023483643342970305, 'p_miss': 0.21122587943808394}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:32:48,110] Trial 112 finished with value: 0.2742786656181266 and parameters: {'model_name': 'VAE', 'batch_size': 193, 'iterations': 15, 'learning_rate': 0.0012700621330600916, 'p_miss': 0.22794167352121175}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:33:44,359] Trial 113 finished with value: 0.2742251570938711 and parameters: {'model_name': 'VAE', 'batch_size': 637, 'iterations': 10, 'learning_rate': 0.0010746663188729232, 'p_miss': 0.1958033037277138}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:33:45,052] Trial 114 finished with value: 0.45635018704939584 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:34:42,880] Trial 115 finished with value: 0.30397796602859306 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 5, 'imputation_order': 'random'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:36:43,162] Trial 116 finished with value: 0.26976671004003827 and parameters: {'model_name': 'VAE', 'batch_size': 378, 'iterations': 33, 'learning_rate': 0.0008461192932024562, 'p_miss': 0.2166604504892251}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:38:08,304] Trial 117 finished with value: 0.2715710666842886 and parameters: {'model_name': 'VAE', 'batch_size': 402, 'iterations': 25, 'learning_rate': 0.0007126126013143662, 'p_miss': 0.2161811681632353}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:39:33,979] Trial 118 finished with value: 0.27252517948143906 and parameters: {'model_name': 'VAE', 'batch_size': 389, 'iterations': 24, 'learning_rate': 0.0006980358813873502, 'p_miss': 0.20853302592332298}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:42:42,687] Trial 119 finished with value: 0.29234185554037573 and parameters: {'model_name': 'VAE', 'batch_size': 248, 'iterations': 57, 'learning_rate': 0.0020546587621227495, 'p_miss': 0.18639043305256303}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:44:13,639] Trial 120 finished with value: 0.27358558324304805 and parameters: {'model_name': 'VAE', 'batch_size': 361, 'iterations': 31, 'learning_rate': 0.00096737714058762, 'p_miss': 0.21587616416182065}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:47:28,525] Trial 121 finished with value: 0.27162802661526786 and parameters: {'model_name': 'VAE', 'batch_size': 221, 'iterations': 83, 'learning_rate': 0.0007671658075679785, 'p_miss': 0.2026541923885001}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:48:13,506] Trial 122 finished with value: 0.2704251516003533 and parameters: {'model_name': 'VAE', 'batch_size': 674, 'iterations': 6, 'learning_rate': 0.002802354169844733, 'p_miss': 0.2301825766511163}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:49:18,142] Trial 123 finished with value: 0.27234083383299634 and parameters: {'model_name': 'VAE', 'batch_size': 818, 'iterations': 6, 'learning_rate': 0.003092134275244892, 'p_miss': 0.24674110663908727}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:50:37,842] Trial 124 finished with value: 0.27377075935447126 and parameters: {'model_name': 'VAE', 'batch_size': 331, 'iterations': 20, 'learning_rate': 0.001691818418283511, 'p_miss': 0.2299450421177947}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:51:32,318] Trial 125 finished with value: 0.2858629032873399 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 18588, 'weights': 'uniform'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:52:00,371] Trial 126 finished with value: 0.27248697228319035 and parameters: {'model_name': 'VAE', 'batch_size': 430, 'iterations': 7, 'learning_rate': 0.0012531401775820372, 'p_miss': 0.2615841338513285}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:54:10,708] Trial 127 finished with value: 0.27104011844207204 and parameters: {'model_name': 'VAE', 'batch_size': 583, 'iterations': 39, 'learning_rate': 0.0005553320652073777, 'p_miss': 0.213231646824917}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:56:45,507] Trial 25 finished with value: 0.2950411313921165 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 5, 'imputation_order': 'arabic'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:57:12,283] Trial 128 finished with value: 0.2869258757001384 and parameters: {'model_name': 'VAE', 'batch_size': 656, 'iterations': 41, 'learning_rate': 0.0023290048282612343, 'p_miss': 0.19846326704662212}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 22:59:49,098] Trial 129 finished with value: 0.2718636888286107 and parameters: {'model_name': 'VAE', 'batch_size': 650, 'iterations': 38, 'learning_rate': 0.000534263676978291, 'p_miss': 0.24277242895038545}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:01:09,771] Trial 130 finished with value: 0.27152519441398837 and parameters: {'model_name': 'VAE', 'batch_size': 658, 'iterations': 51, 'learning_rate': 0.0005366641608187449, 'p_miss': 0.24196782882324117}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:01:41,010] Trial 132 finished with value: 0.4364921384739143 and parameters: {'model_name': 'GAIN', 'batch_size': 246, 'hint_rate': 0.7639916307178203, 'alpha': 27, 'iterations': 18, 'learning_rate': 0.0011029070664084603, 'p_miss': 0.22958363981591914}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:02:40,678] Trial 131 finished with value: 0.2715053370421041 and parameters: {'model_name': 'VAE', 'batch_size': 269, 'iterations': 51, 'learning_rate': 0.001015678118790104, 'p_miss': 0.23129932481962884}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:05:22,005] Trial 17 finished with value: 0.29882206420181545 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 4674, 'learning_rate': 0.00017921083891744394, 'p_miss': 0.13791292166251437}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:05:34,717] Trial 101 finished with value: 0.31373533411398163 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'ascending'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:06:16,873] Trial 134 finished with value: 0.2817969243866284 and parameters: {'model_name': 'VAE', 'batch_size': 144, 'iterations': 67, 'learning_rate': 0.0014102985221770377, 'p_miss': 0.2102001707434851}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:06:20,311] Trial 133 finished with value: 0.29534639333437895 and parameters: {'model_name': 'VAE', 'batch_size': 147, 'iterations': 102, 'learning_rate': 0.0028691824939522286, 'p_miss': 0.20709155517325029}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:06:56,352] Trial 138 finished with value: 0.27265429339048103 and parameters: {'model_name': 'VAE', 'batch_size': 204, 'iterations': 11, 'learning_rate': 0.0010026364581155259, 'p_miss': 0.2245501371240886}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:08:25,469] Trial 139 finished with value: 0.27271198847945205 and parameters: {'model_name': 'VAE', 'batch_size': 284, 'iterations': 27, 'learning_rate': 0.0005886709747290696, 'p_miss': 0.23274380014515333}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:10:32,145] Trial 136 finished with value: 0.27527443847474514 and parameters: {'model_name': 'VAE', 'batch_size': 294, 'iterations': 63, 'learning_rate': 0.0009061324088797624, 'p_miss': 0.2131552906262981}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:11:01,213] Trial 140 finished with value: 0.27105914961183364 and parameters: {'model_name': 'VAE', 'batch_size': 455, 'iterations': 36, 'learning_rate': 0.0008775886921654534, 'p_miss': 0.25236539567122696}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:13:43,387] Trial 142 finished with value: 0.27822897174361144 and parameters: {'model_name': 'VAE', 'batch_size': 445, 'iterations': 35, 'learning_rate': 0.001930117196652334, 'p_miss': 0.2563437369027763}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:14:28,146] Trial 143 finished with value: 0.272768542580652 and parameters: {'model_name': 'VAE', 'batch_size': 92, 'iterations': 17, 'learning_rate': 0.0008053134848718995, 'p_miss': 0.17849325863815393}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:14:29,307] Trial 144 finished with value: 0.3784595419050992 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:15:19,534] Trial 135 finished with value: 0.2959752531887487 and parameters: {'model_name': 'VAE', 'batch_size': 139, 'iterations': 181, 'learning_rate': 0.0014178122463539484, 'p_miss': 0.20736022485680056}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:16:17,747] Trial 145 finished with value: 0.2729868875406338 and parameters: {'model_name': 'VAE', 'batch_size': 726, 'iterations': 20, 'learning_rate': 0.0006437163678211232, 'p_miss': 0.21943576916169266}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:16:29,763] Trial 137 finished with value: 0.29299893141302624 and parameters: {'model_name': 'VAE', 'batch_size': 304, 'iterations': 162, 'learning_rate': 0.0009633310840554561, 'p_miss': 0.23404340634342252}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:19:29,394] Trial 146 finished with value: 0.27336073528102955 and parameters: {'model_name': 'VAE', 'batch_size': 986, 'iterations': 46, 'learning_rate': 0.0004605042462357231, 'p_miss': 0.23539991311972558}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:19:51,566] Trial 147 finished with value: 0.27153371979980967 and parameters: {'model_name': 'VAE', 'batch_size': 551, 'iterations': 48, 'learning_rate': 0.00047746582803661036, 'p_miss': 0.23554609244677036}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:21:00,425] Trial 148 finished with value: 0.2747070177526599 and parameters: {'model_name': 'VAE', 'batch_size': 894, 'iterations': 46, 'learning_rate': 0.0011889400133029196, 'p_miss': 0.2522545164540845}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:23:17,350] Trial 141 finished with value: 0.29622031962612133 and parameters: {'model_name': 'VAE', 'batch_size': 975, 'iterations': 151, 'learning_rate': 0.0017687487828197384, 'p_miss': 0.25632011559468976}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:25:02,356] Trial 152 finished with value: 0.2708960197133591 and parameters: {'model_name': 'VAE', 'batch_size': 179, 'iterations': 29, 'learning_rate': 0.0006411337711272418, 'p_miss': 0.22566743104442466}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:25:07,079] Trial 149 finished with value: 0.28318470214748526 and parameters: {'model_name': 'VAE', 'batch_size': 460, 'iterations': 95, 'learning_rate': 0.0012022026523095337, 'p_miss': 0.24821852759903879}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:25:33,149] Trial 150 finished with value: 0.28164031313989246 and parameters: {'model_name': 'VAE', 'batch_size': 352, 'iterations': 91, 'learning_rate': 0.0011072780124563686, 'p_miss': 0.2503541438305569}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:26:30,859] Trial 155 finished with value: 0.28703316199397955 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 24337, 'weights': 'uniform'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:26:40,605] Trial 153 finished with value: 0.2698939465115605 and parameters: {'model_name': 'VAE', 'batch_size': 181, 'iterations': 30, 'learning_rate': 0.0007822959363000622, 'p_miss': 0.2207255228151812}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:26:51,024] Trial 154 finished with value: 0.28269915431982107 and parameters: {'model_name': 'VAE', 'batch_size': 194, 'iterations': 31, 'learning_rate': 0.003822109011599503, 'p_miss': 0.1924668936119914}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:27:18,586] Trial 158 finished with value: 0.27607130332360236 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 9, 'learning_rate': 0.0006388144614575837, 'p_miss': 0.22389775121950575}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:27:25,052] Trial 151 finished with value: 0.292737257922039 and parameters: {'model_name': 'VAE', 'batch_size': 445, 'iterations': 98, 'learning_rate': 0.0016696541375983602, 'p_miss': 0.18916632188992039}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:28:26,752] Trial 156 finished with value: 0.295666262868151 and parameters: {'model_name': 'VAE', 'batch_size': 180, 'iterations': 33, 'learning_rate': 0.07414898248057854, 'p_miss': 0.22425612060036776}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:28:33,825] Trial 160 finished with value: 0.295370689663896 and parameters: {'model_name': 'VAE', 'batch_size': 184, 'iterations': 14, 'learning_rate': 0.07076862830499338, 'p_miss': 0.21631895417690974}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:28:48,387] Trial 159 finished with value: 0.27212631989628333 and parameters: {'model_name': 'VAE', 'batch_size': 165, 'iterations': 29, 'learning_rate': 0.0008267530785132684, 'p_miss': 0.2175323962040843}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:28:57,778] Trial 157 finished with value: 0.271611067253399 and parameters: {'model_name': 'VAE', 'batch_size': 167, 'iterations': 30, 'learning_rate': 0.0005905711111868899, 'p_miss': 0.2189591436981973}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:29:16,039] Trial 162 finished with value: 0.4369792316867505 and parameters: {'model_name': 'GAIN', 'batch_size': 357, 'hint_rate': 0.3191247214863662, 'alpha': 0, 'iterations': 24, 'learning_rate': 0.0008240008961955209, 'p_miss': 0.202764602956497}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:29:27,500] Trial 161 finished with value: 0.27157608416260315 and parameters: {'model_name': 'VAE', 'batch_size': 340, 'iterations': 14, 'learning_rate': 0.0008483964784140223, 'p_miss': 0.21679577405860942}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:29:27,735] Trial 163 finished with value: 0.44884181825182623 and parameters: {'model_name': 'GAIN', 'batch_size': 233, 'hint_rate': 0.28844461191201426, 'alpha': 7, 'iterations': 24, 'learning_rate': 0.0007327415135869391, 'p_miss': 0.09600648699762529}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:29:45,452] Trial 165 finished with value: 0.2751736305017644 and parameters: {'model_name': 'VAE', 'batch_size': 221, 'iterations': 6, 'learning_rate': 0.0026658270729432894, 'p_miss': 0.23791948793140982}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:31:05,679] Trial 164 finished with value: 0.2753216260393636 and parameters: {'model_name': 'VAE', 'batch_size': 566, 'iterations': 23, 'learning_rate': 0.002652742022256101, 'p_miss': 0.08868494135112465}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:31:32,011] Trial 166 finished with value: 0.27296794781575556 and parameters: {'model_name': 'VAE', 'batch_size': 249, 'iterations': 39, 'learning_rate': 0.0006788494224499262, 'p_miss': 0.23031329578597776}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:32:13,608] Trial 168 finished with value: 0.2711904663021892 and parameters: {'model_name': 'VAE', 'batch_size': 265, 'iterations': 40, 'learning_rate': 0.0013631963063792882, 'p_miss': 0.22885507302532418}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:05,458] Trial 167 finished with value: 0.2742925469732591 and parameters: {'model_name': 'VAE', 'batch_size': 573, 'iterations': 57, 'learning_rate': 0.0013538851947053128, 'p_miss': 0.24023694826207753}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:10,279] Trial 169 finished with value: 0.2779541846625013 and parameters: {'model_name': 'VAE', 'batch_size': 274, 'iterations': 38, 'learning_rate': 0.0021468494963654662, 'p_miss': 0.22754701749091452}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:32,966] Trial 170 finished with value: 0.3068719435670789 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 56, 'learning_rate': 0.0073953660142368274, 'p_miss': 0.22783188929576864}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:35,479] Trial 172 finished with value: 0.27087318573323305 and parameters: {'model_name': 'VAE', 'batch_size': 409, 'iterations': 11, 'learning_rate': 0.0015814163553307626, 'p_miss': 0.21180614083224156}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:36,545] Trial 175 finished with value: 0.292634309674553 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:44,126] Trial 174 finished with value: 0.2788792525735457 and parameters: {'model_name': 'VAE', 'batch_size': 407, 'iterations': 4, 'learning_rate': 0.001520379575646968, 'p_miss': 0.21140477136795296}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:33:52,672] Trial 173 finished with value: 0.2820256857206304 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 7, 'imputation_order': 'roman'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:34:16,548] Trial 176 finished with value: 0.27362641722634223 and parameters: {'model_name': 'VAE', 'batch_size': 408, 'iterations': 10, 'learning_rate': 0.0015828940542365346, 'p_miss': 0.21154116529499678}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:34:31,823] Trial 177 finished with value: 0.27496078622398884 and parameters: {'model_name': 'VAE', 'batch_size': 771, 'iterations': 7, 'learning_rate': 0.0018478110044232053, 'p_miss': 0.20431339367419374}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:34:36,439] Trial 179 finished with value: 0.2762101679372082 and parameters: {'model_name': 'VAE', 'batch_size': 82, 'iterations': 7, 'learning_rate': 0.0003850825793024168, 'p_miss': 0.15975531555761985}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:34:43,116] Trial 178 finished with value: 0.27507507246374807 and parameters: {'model_name': 'VAE', 'batch_size': 505, 'iterations': 7, 'learning_rate': 0.0016564455682103439, 'p_miss': 0.20215801030268396}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:35:42,306] Trial 180 finished with value: 0.27351683847488795 and parameters: {'model_name': 'VAE', 'batch_size': 475, 'iterations': 18, 'learning_rate': 0.00039334588792137393, 'p_miss': 0.22371542355486598}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:35:49,801] Trial 182 finished with value: 0.2714530038894966 and parameters: {'model_name': 'VAE', 'batch_size': 131, 'iterations': 18, 'learning_rate': 0.0012816715938126014, 'p_miss': 0.22339462746521335}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:35:54,705] Trial 181 finished with value: 0.27571746647117207 and parameters: {'model_name': 'VAE', 'batch_size': 486, 'iterations': 20, 'learning_rate': 0.0009931606371096394, 'p_miss': 0.19910253152752988}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:36:18,931] Trial 171 finished with value: 0.2912218262557782 and parameters: {'model_name': 'VAE', 'batch_size': 420, 'iterations': 57, 'learning_rate': 0.0021336317382234992, 'p_miss': 0.24097443308047797}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:37:13,437] Trial 186 finished with value: 0.27155524047731733 and parameters: {'model_name': 'VAE', 'batch_size': 119, 'iterations': 13, 'learning_rate': 0.001243198769157766, 'p_miss': 0.2230686313322219}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:38:01,401] Trial 187 finished with value: 0.2717885718059089 and parameters: {'model_name': 'VAE', 'batch_size': 324, 'iterations': 11, 'learning_rate': 0.0011104388126350975, 'p_miss': 0.21593706909224641}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:39:02,749] Trial 188 finished with value: 0.2696256694931476 and parameters: {'model_name': 'VAE', 'batch_size': 96, 'iterations': 16, 'learning_rate': 0.0013556931417838271, 'p_miss': 0.22081746117269765}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:40:35,249] Trial 189 finished with value: 0.2707601163451419 and parameters: {'model_name': 'VAE', 'batch_size': 141, 'iterations': 28, 'learning_rate': 0.001334293416495569, 'p_miss': 0.2676937624896696}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:40:50,002] Trial 183 finished with value: 0.27994489438213754 and parameters: {'model_name': 'VAE', 'batch_size': 321, 'iterations': 77, 'learning_rate': 0.0010098364099299826, 'p_miss': 0.22135231913634057}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:41:45,555] Trial 190 finished with value: 0.2715397654876751 and parameters: {'model_name': 'VAE', 'batch_size': 98, 'iterations': 21, 'learning_rate': 0.0009574193920411451, 'p_miss': 0.2839804164843252}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:42:00,012] Trial 191 finished with value: 0.2725800222202535 and parameters: {'model_name': 'VAE', 'batch_size': 133, 'iterations': 20, 'learning_rate': 0.0013725314006944476, 'p_miss': 0.29620963537893386}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:43:12,350] Trial 192 finished with value: 0.2897100200820972 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 47762, 'weights': 'distance'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:43:13,403] Trial 193 finished with value: 0.2897401361418003 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 61447, 'weights': 'distance'}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:44:47,187] Trial 194 finished with value: 0.27145480415161855 and parameters: {'model_name': 'VAE', 'batch_size': 122, 'iterations': 27, 'learning_rate': 0.0007391239513272978, 'p_miss': 0.11548984354656303}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:44:56,048] Trial 195 finished with value: 0.2755594256473932 and parameters: {'model_name': 'VAE', 'batch_size': 127, 'iterations': 27, 'learning_rate': 0.0007548036203363633, 'p_miss': 0.2746870268059453}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:45:35,878] Trial 196 finished with value: 0.2745167185386872 and parameters: {'model_name': 'VAE', 'batch_size': 78, 'iterations': 16, 'learning_rate': 0.0007694994972273904, 'p_miss': 0.23128474874105484}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:45:49,337] Trial 197 finished with value: 0.28074098260075997 and parameters: {'model_name': 'VAE', 'batch_size': 156, 'iterations': 16, 'learning_rate': 0.000545651520382505, 'p_miss': 0.26449921683992417}. Best is trial 94 with value: 0.2670577963286633.
running
[I 2024-10-04 23:47:40,972] Trial 198 finished with value: 0.27516450298534767 and parameters: {'model_name': 'VAE', 'batch_size': 156, 'iterations': 41, 'learning_rate': 0.0004991959500280625, 'p_miss': 0.1776881776059344}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-04 23:47:43,346] Trial 199 finished with value: 0.27401490901028847 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 38, 'learning_rate': 0.0006367204648507376, 'p_miss': 0.21488989137314318}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:03:35,069] Trial 27 finished with value: 0.2960076524599541 and parameters: {'model_name': 'VAE', 'batch_size': 82, 'iterations': 7012, 'learning_rate': 0.0011345714005363914, 'p_miss': 0.021982940882477396}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:23:41,083] Trial 102 finished with value: 0.31267917696850883 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'ascending'}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:31:29,750] Trial 185 finished with value: 0.29656844131329013 and parameters: {'model_name': 'VAE', 'batch_size': 132, 'iterations': 1764, 'learning_rate': 0.0013037986986409724, 'p_miss': 0.21432813245544144}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:37:14,792] Trial 85 finished with value: 0.29517440233149506 and parameters: {'model_name': 'VAE', 'batch_size': 28, 'iterations': 6301, 'learning_rate': 0.005906775489996604, 'p_miss': 0.0412602779689186}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:47:36,318] Trial 56 finished with value: 0.2809044021940398 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:48:01,894] Trial 55 finished with value: 0.2808322914497202 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 00:49:18,926] Trial 57 finished with value: 0.2807423099127182 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:03:28,291] Trial 87 finished with value: 0.29440522213514403 and parameters: {'model_name': 'VAE', 'batch_size': 35, 'iterations': 7679, 'learning_rate': 0.0014184415965950523, 'p_miss': 0.18821645402876605}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:05:07,874] Trial 1 finished with value: 0.2964826164236444 and parameters: {'model_name': 'VAE', 'batch_size': 156, 'iterations': 8551, 'learning_rate': 0.006346390721461652, 'p_miss': 0.19624773083011052}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:09:31,735] Trial 30 finished with value: 0.2954261182429304 and parameters: {'model_name': 'VAE', 'batch_size': 27, 'iterations': 9252, 'learning_rate': 0.0004066673730765366, 'p_miss': 0.28997550800727456}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:18:42,526] Trial 77 finished with value: 0.29608087667693256 and parameters: {'model_name': 'VAE', 'batch_size': 183, 'iterations': 9961, 'learning_rate': 0.00019831934931668452, 'p_miss': 0.23043028804294274}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:19:11,617] Trial 86 finished with value: 0.2966076061355333 and parameters: {'model_name': 'VAE', 'batch_size': 31, 'iterations': 9217, 'learning_rate': 0.0011749390923843162, 'p_miss': 0.18752610455495933}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:24:57,743] Trial 184 finished with value: 0.2953882712352901 and parameters: {'model_name': 'VAE', 'batch_size': 124, 'iterations': 8511, 'learning_rate': 0.0009752180796553285, 'p_miss': 0.240293163493511}. Best is trial 94 with value: 0.2670577963286633.
[I 2024-10-05 01:32:25,166] Trial 42 finished with value: 0.29667225098686634 and parameters: {'model_name': 'VAE', 'batch_size': 948, 'iterations': 8544, 'learning_rate': 0.006074274464780465, 'p_miss': 0.17249447042322696}. Best is trial 94 with value: 0.2670577963286633.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64
0.2670577963286633
{'model_name': 'VAE', 'batch_size': 122, 'iterations': 59, 'learning_rate': 0.0008653051043608123, 'p_miss': 0.2180905494473802}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b20> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  1
Best root_mean_squared_error score: -10.204210287094607
Generation:   4%|▍         | 1/25 [01:34<37:46, 94.42s/it]Generation:  2
Best root_mean_squared_error score: -10.204210287094607
Generation:   8%|▊         | 2/25 [04:33<55:14, 144.12s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f9e710> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  3
Best root_mean_squared_error score: -10.204210287094607
Generation:  12%|█▏        | 3/25 [10:55<1:32:43, 252.87s/it]Generation:  4
Best root_mean_squared_error score: -10.204210287094607
Generation:  16%|█▌        | 4/25 [12:20<1:05:15, 186.44s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a61d0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f56290> 

Generation:  5
Best root_mean_squared_error score: -10.201256468526703
Generation:  20%|██        | 5/25 [22:23<1:52:11, 336.58s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f9b700> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f006a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -10.19882082942173
Generation:  24%|██▍       | 6/25 [22:53<1:13:35, 232.37s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e22c20> 

Generation:  7
Best root_mean_squared_error score: -10.19882082942173
Generation:  28%|██▊       | 7/25 [32:57<1:46:14, 354.14s/it]Generation:  8
Best root_mean_squared_error score: -10.19882082942173
Generation:  32%|███▏      | 8/25 [38:55<1:40:38, 355.18s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746aa260> 

Generation:  9
Best root_mean_squared_error score: -10.19882082942173
Generation:  36%|███▌      | 9/25 [49:00<1:55:35, 433.44s/it]Generation:  10
Best root_mean_squared_error score: -10.19882082942173
Generation:  40%|████      | 10/25 [54:27<1:40:06, 400.47s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678e93f0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  11
Best root_mean_squared_error score: -10.19882082942173
Generation:  44%|████▍     | 11/25 [56:02<1:11:36, 306.93s/it]Generation:  12
Best root_mean_squared_error score: -10.19882082942173
Generation:  48%|████▊     | 12/25 [59:15<59:00, 272.34s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472c850> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  13
Best root_mean_squared_error score: -10.19882082942173
Generation:  52%|█████▏    | 13/25 [1:00:11<41:20, 206.70s/it]Generation:  14
Best root_mean_squared_error score: -10.19882082942173
Generation:  56%|█████▌    | 14/25 [1:05:44<44:54, 244.95s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e44a60> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -10.19882082942173
Generation:  60%|██████    | 15/25 [1:06:04<29:31, 177.11s/it]Generation:  16
Best root_mean_squared_error score: -10.19882082942173
Generation:  64%|██████▍   | 16/25 [1:07:57<23:39, 157.72s/it]Generation:  17
Best root_mean_squared_error score: -10.19882082942173
Generation:  68%|██████▊   | 17/25 [1:10:55<21:52, 164.05s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155458626da0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467da18a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  18
Best root_mean_squared_error score: -10.19882082942173
Generation:  72%|███████▏  | 18/25 [1:15:05<22:08, 189.73s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466bf5ea0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  19
Best root_mean_squared_error score: -10.19882082942173
Generation:  76%|███████▌  | 19/25 [1:20:54<23:45, 237.62s/it]Generation:  20
Best root_mean_squared_error score: -10.19882082942173
Generation:  80%|████████  | 20/25 [1:24:23<19:05, 229.12s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467918160> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  21
Best root_mean_squared_error score: -10.19882082942173
Generation:  84%|████████▍ | 21/25 [1:28:55<16:07, 241.98s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ce6020> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678a9b70> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d37250> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -10.19882082942173
Generation:  88%|████████▊ | 22/25 [1:34:24<13:24, 268.11s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554675c5ab0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  23
Best root_mean_squared_error score: -10.19882082942173
Generation:  92%|█████████▏| 23/25 [1:37:51<08:19, 249.52s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474730370> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546745ae90> 

Generation:  24
Best root_mean_squared_error score: -10.19882082942173
Generation:  96%|█████████▌| 24/25 [1:48:01<05:57, 357.67s/it]Generation:  25
Best root_mean_squared_error score: -10.19882082942173
Generation: 100%|██████████| 25/25 [1:49:05<00:00, 269.74s/it]Generation: 100%|██████████| 25/25 [1:49:08<00:00, 261.92s/it]
2024-10-05 03:21:50,466 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:41889' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-1d0e009188a2b3d312df111cad3e0148', 'DataFrame-9b492617203538632e42fe3a58de2d85'} (stimulus_id='handle-worker-cleanup-1728123710.466145')
Fitted
Pipeline(steps=[('lgbmregressor',
                 LGBMRegressor(max_depth=6, n_estimators=71, n_jobs=1,
                               num_leaves=5, verbose=-1))])
score start
train score: {'explained_var': 0.04010443981798495, 'r2': 0.04010443981798517, 'rmse': 10.172141031545443}
original test score: {'explained_var': 0.01877694599069002, 'r2': 0.009109764718835511, 'rmse': 10.365211548636719}
imputed test score: {'explained_var': -0.024581796183072768, 'r2': -0.03064811344613738, 'rmse': 10.571110249026793}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x155434d3faf0>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b20> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4fd0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4070> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a41c0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b80> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b50> 

Generation:  1
Best root_mean_squared_error score: -8.650814777996752
Generation:   4%|▍         | 1/25 [10:02<4:01:01, 602.56s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466b6f520> 
 Input X contains NaN.
AdaBoostRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 133, in fit
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
AdaBoostRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  2
Best root_mean_squared_error score: -8.400481291200899
Generation:   8%|▊         | 2/25 [14:43<2:38:27, 413.36s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554642d3070> 

Generation:  3
Best root_mean_squared_error score: -8.400481291200899
Generation:  12%|█▏        | 3/25 [24:47<3:03:32, 500.59s/it]Generation:  4
Best root_mean_squared_error score: -8.400481291200899
Generation:  16%|█▌        | 4/25 [26:03<1:56:31, 332.94s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464f560b0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464f54f40> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a7a30> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464857670> 

Generation:  5
Best root_mean_squared_error score: -8.400481291200899
Generation:  20%|██        | 5/25 [36:07<2:23:35, 430.75s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467dac6a0> 

Generation:  6
Best root_mean_squared_error score: -8.375561763697442
Generation:  24%|██▍       | 6/25 [46:11<2:34:59, 489.45s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470e590> 

Generation:  7
Best root_mean_squared_error score: -8.369069119396451
Generation:  28%|██▊       | 7/25 [56:14<2:38:01, 526.77s/it]Generation:  8
Best root_mean_squared_error score: -8.369069119396451
Generation:  32%|███▏      | 8/25 [1:01:16<2:08:58, 455.20s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b94070> 

Generation:  9
Best root_mean_squared_error score: -8.369069119396451
Generation:  36%|███▌      | 9/25 [1:11:21<2:13:52, 502.03s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554513a8280> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464474af0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155453152890> 

Generation:  10
Best root_mean_squared_error score: -8.369069119396451
Generation:  40%|████      | 10/25 [1:21:26<2:13:23, 533.55s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472a080> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554528a6410> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ce5420> 

Generation:  11
Best root_mean_squared_error score: -8.369069119396451
Generation:  44%|████▍     | 11/25 [1:31:30<2:09:34, 555.32s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464fa6590> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454562a70> 

Generation:  12
Best root_mean_squared_error score: -8.369069119396451
Generation:  48%|████▊     | 12/25 [1:41:33<2:03:27, 569.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f6650> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464f556f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464244400> 

Generation:  13
Best root_mean_squared_error score: -8.369069119396451
Generation:  52%|█████▏    | 13/25 [1:51:37<1:56:02, 580.25s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554658c09a0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466b2f850> 

Generation:  14
Best root_mean_squared_error score: -8.369069119396451
Generation:  56%|█████▌    | 14/25 [2:01:41<1:47:41, 587.40s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155451c54f10> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a62da0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155451194fa0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554642cbf10> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467d63880> 

Generation:  15
Best root_mean_squared_error score: -8.369069119396451
Generation:  60%|██████    | 15/25 [2:11:46<1:38:46, 592.68s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554659ed900> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  16
Best root_mean_squared_error score: -8.369069119396451
Generation:  64%|██████▍   | 16/25 [2:13:56<1:07:59, 453.26s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155466935cc0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474712380> 

Generation:  17
Best root_mean_squared_error score: -8.369069119396451
Generation:  68%|██████▊   | 17/25 [2:24:01<1:06:30, 498.87s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1552ac693820> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  18
Best root_mean_squared_error score: -8.369069119396451
Generation:  72%|███████▏  | 18/25 [2:24:18<41:18, 354.04s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554513afdc0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464253520> 

Generation:  19
Best root_mean_squared_error score: -8.369069119396451
Generation:  76%|███████▌  | 19/25 [2:34:21<42:53, 428.96s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554679fafb0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  20
Best root_mean_squared_error score: -8.369069119396451
Generation:  80%|████████  | 20/25 [2:37:31<29:45, 357.11s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f205e0> 

Generation:  21
Best root_mean_squared_error score: -8.369069119396451
Generation:  84%|████████▍ | 21/25 [2:47:34<28:44, 431.11s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f04df0> 

Generation:  22
Best root_mean_squared_error score: -8.369069119396451
Generation:  88%|████████▊ | 22/25 [2:57:37<24:07, 482.64s/it]Generation:  23
Best root_mean_squared_error score: -8.369069119396451
Generation:  92%|█████████▏| 23/25 [2:58:00<11:29, 344.70s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f66b0> 

Generation:  24
Best root_mean_squared_error score: -8.369069119396451
Generation:  96%|█████████▌| 24/25 [3:08:04<07:02, 422.39s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155464e3fc70> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465a06dd0> 

Generation:  25
Best root_mean_squared_error score: -8.369069119396451
Generation: 100%|██████████| 25/25 [3:18:07<00:00, 476.52s/it]Generation: 100%|██████████| 25/25 [3:18:07<00:00, 475.49s/it]
2024-10-05 06:40:12,084 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:41271' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-0f88c5be833b523f596afd5be3a28e90', 'DataFrame-9b492617203538632e42fe3a58de2d85'} (stimulus_id='handle-worker-cleanup-1728135612.0848997')
Fitted
Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('xgbregressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature_types=None, gamma=0.0206620676009,
                              grow_policy=None, importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.0668939107004, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=4, max_leaves=None,
                              min_child_weight=6, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=1, nthread=1,
                              num_parallel_tree=None, ...))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.3616594266048876, 'r2': 0.3616594076156616, 'rmse': 8.295195495315097}
test score: {'explained_var': 0.20514307086610317, 'r2': 0.20513993501663208, 'rmse': 9.283478272466853}
original test score: {'explained_var': 0.2527935008359138, 'r2': 0.2522839307785034, 'rmse': 9.003964102654487}
score end
1213
lvl
0.5
type
MAR
num_run
3
reg_full
finished
all finished
full run takes
10.6875700010856
hours
DONE
