Run: 28
/cm/local/apps/slurm/var/spool/job1044078/slurm_script: line 27: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
starting loops
../data/c/1507/1507.pkl
working on 
../data/c/1507/class_full_MCAR_0.5_2
3.209373950958252
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-11-08 10:14:13,259] A new study created in memory with name: no-name-b5ae7289-bf8b-40b5-8ef8-577784c28b48
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-11-08 10:14:13,571] Trial 1 finished with value: 0.20134806053815119 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:13,825] Trial 11 finished with value: 0.20134806053815119 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 1 with value: 0.20134806053815119.
[I 2024-11-08 10:14:13,935] Trial 9 finished with value: 0.320565805494184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 1 with value: 0.20134806053815119.
[I 2024-11-08 10:14:14,045] Trial 0 finished with value: 0.320565805494184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 1 with value: 0.20134806053815119.
running
running
running
[I 2024-11-08 10:14:14,269] Trial 12 finished with value: 0.320565805494184 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:14,395] Trial 17 finished with value: 0.20134806053815119 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:14,808] Trial 18 finished with value: 0.20134806053815119 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:15,114] Trial 10 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:18,555] Trial 6 finished with value: 0.20134806053815119 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5386, 'weights': 'uniform'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:20,530] Trial 21 finished with value: 0.208950891528168 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 301, 'weights': 'distance'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:21,155] Trial 2 finished with value: 0.20550600557038004 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2882, 'weights': 'uniform'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:22,355] Trial 23 finished with value: 0.20811635828867772 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1100, 'weights': 'distance'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:23,140] Trial 19 finished with value: 0.2039692324775512 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3828, 'weights': 'distance'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:23,580] Trial 8 finished with value: 0.20269333938871986 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4343, 'weights': 'distance'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:25,495] Trial 24 finished with value: 0.20837721881088012 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 841, 'weights': 'distance'}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:28,327] Trial 14 finished with value: 0.3456863596727898 and parameters: {'model_name': 'GAIN', 'batch_size': 14, 'hint_rate': 0.9511465308425673, 'alpha': 93, 'iterations': 1, 'learning_rate': 0.0008770261295027724, 'p_miss': 0.12567338354529856}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:44,095] Trial 13 finished with value: 0.3518196010940365 and parameters: {'model_name': 'GAIN', 'batch_size': 27, 'hint_rate': 0.6604377804058735, 'alpha': 31, 'iterations': 24, 'learning_rate': 0.008014676710370433, 'p_miss': 0.12774658087331267}. Best is trial 1 with value: 0.20134806053815119.
running
[I 2024-11-08 10:14:45,265] Trial 16 finished with value: 0.10977873205078421 and parameters: {'model_name': 'VAE', 'batch_size': 46, 'iterations': 16, 'learning_rate': 0.0007140021920649731, 'p_miss': 0.1306776719250609}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:14:47,231] Trial 30 finished with value: 0.20091185425865915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:15:40,692] Trial 27 finished with value: 0.20916666816198556 and parameters: {'model_name': 'VAE', 'batch_size': 34, 'iterations': 72, 'learning_rate': 0.010980239241227768, 'p_miss': 0.03198882586031335}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:00,661] Trial 35 finished with value: 0.20091185622724606 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:23,875] Trial 36 finished with value: 0.20091185425865915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:30,738] Trial 28 finished with value: 0.20961237667305918 and parameters: {'model_name': 'VAE', 'batch_size': 97, 'iterations': 105, 'learning_rate': 0.011399939370829955, 'p_miss': 0.10547326312387537}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:42,064] Trial 29 finished with value: 0.20120325403912664 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 6, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:48,882] Trial 37 finished with value: 0.20091185425865915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:16:57,727] Trial 38 finished with value: 0.20091185425865915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:17:08,948] Trial 39 finished with value: 0.20091185425865915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:17:17,835] Trial 31 finished with value: 0.27335462840857633 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:17:37,790] Trial 7 finished with value: 0.2745793553343676 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:17:42,948] Trial 40 finished with value: 0.20090649377412023 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 14, 'imputation_order': 'roman'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:17:57,666] Trial 4 finished with value: 0.27660601599802376 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:19:47,948] Trial 5 finished with value: 0.21153186089668324 and parameters: {'model_name': 'VAE', 'batch_size': 10, 'iterations': 256, 'learning_rate': 0.0025933460195642862, 'p_miss': 0.16053896903034862}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 10:30:08,008] Trial 26 finished with value: 0.20859009228451492 and parameters: {'model_name': 'VAE', 'batch_size': 127, 'iterations': 365, 'learning_rate': 0.0004666377812319459, 'p_miss': 0.28019193808570275}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:30:12,012] Trial 22 finished with value: 0.34658258096641603 and parameters: {'model_name': 'GAIN', 'batch_size': 218, 'hint_rate': 0.9591935542667498, 'alpha': 77, 'iterations': 2930, 'learning_rate': 0.0002587877775444172, 'p_miss': 0.22220289566517185}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:31:22,824] Trial 49 finished with value: 0.22253830514669798 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'roman'}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:31:34,078] Trial 50 finished with value: 0.11409304873153307 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 3, 'learning_rate': 0.00010358376821948614, 'p_miss': 0.03530407142232285}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:31:46,112] Trial 51 finished with value: 0.11715765024852283 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 3, 'learning_rate': 0.00010827714337524678, 'p_miss': 0.021213735870705602}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:31:57,150] Trial 52 finished with value: 0.11306070929585743 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 3, 'learning_rate': 0.00010333158286317155, 'p_miss': 0.010405820980654203}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:32:07,952] Trial 53 finished with value: 0.11141149761991531 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 3, 'learning_rate': 0.00011207121621153544, 'p_miss': 0.015779918459932412}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:32:32,095] Trial 54 finished with value: 0.11737110655828464 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 6, 'learning_rate': 0.00010107704660133639, 'p_miss': 0.011363802222031262}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:33:00,139] Trial 55 finished with value: 0.11405446806454175 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 7, 'learning_rate': 0.00019458626221487734, 'p_miss': 0.06506827432000917}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:33:27,759] Trial 56 finished with value: 0.11697236760584082 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 7, 'learning_rate': 0.00012065665517447411, 'p_miss': 0.06379743110740313}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:33:36,809] Trial 57 finished with value: 0.11794907078371779 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 2, 'learning_rate': 0.00030226515115524204, 'p_miss': 0.061362487781300684}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:34:23,002] Trial 58 finished with value: 0.11426240057754371 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 13, 'learning_rate': 0.00020571918510539253, 'p_miss': 0.05812047112864498}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:34:27,671] Trial 59 finished with value: 0.11427198907704132 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 1, 'learning_rate': 0.0008533022433970169, 'p_miss': 0.01735673809751257}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:34:40,875] Trial 60 finished with value: 0.11648796759020034 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 4, 'learning_rate': 0.00010501328833589457, 'p_miss': 0.05669683224330197}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:35:52,395] Trial 61 finished with value: 0.11619589120827248 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 19, 'learning_rate': 0.0002603337400020976, 'p_miss': 0.08295775350156956}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:36:09,669] Trial 62 finished with value: 0.11063829016762457 and parameters: {'model_name': 'VAE', 'batch_size': 853, 'iterations': 2, 'learning_rate': 0.0006275700039785171, 'p_miss': 0.17216699786124356}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:36:18,013] Trial 63 finished with value: 0.1174803916164637 and parameters: {'model_name': 'VAE', 'batch_size': 806, 'iterations': 1, 'learning_rate': 0.0006980394535913867, 'p_miss': 0.17789856538888776}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:36:49,214] Trial 64 finished with value: 0.11188228102086602 and parameters: {'model_name': 'VAE', 'batch_size': 8, 'iterations': 11, 'learning_rate': 0.0023156577548093023, 'p_miss': 0.18698664425258094}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:39:18,771] Trial 65 finished with value: 0.1613119652012048 and parameters: {'model_name': 'VAE', 'batch_size': 809, 'iterations': 24, 'learning_rate': 0.002237589587600117, 'p_miss': 0.20462635541208438}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:39:41,498] Trial 66 finished with value: 0.11435075928801819 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 8, 'learning_rate': 0.001294536423671364, 'p_miss': 0.19888471918313466}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:39:55,915] Trial 67 finished with value: 0.23041590119869473 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 2, 'learning_rate': 0.0555332419639183, 'p_miss': 0.16474114324073805}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:40:24,327] Trial 68 finished with value: 0.11531471170321461 and parameters: {'model_name': 'VAE', 'batch_size': 4, 'iterations': 10, 'learning_rate': 0.0004328628727736797, 'p_miss': 0.238367353017079}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:41:21,136] Trial 69 finished with value: 0.3423881413073889 and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.020831570094524077, 'alpha': 1, 'iterations': 37, 'learning_rate': 0.00018974359961128172, 'p_miss': 0.13219819343684175}. Best is trial 16 with value: 0.10977873205078421.
running
[I 2024-11-08 11:41:47,378] Trial 70 finished with value: 0.10929277230315501 and parameters: {'model_name': 'VAE', 'batch_size': 331, 'iterations': 4, 'learning_rate': 0.0016969728375927672, 'p_miss': 0.17754813605811706}. Best is trial 70 with value: 0.10929277230315501.
running
[I 2024-11-08 11:42:09,901] Trial 71 finished with value: 0.10789945061154911 and parameters: {'model_name': 'VAE', 'batch_size': 548, 'iterations': 2, 'learning_rate': 0.0015532247774666, 'p_miss': 0.1868746408420931}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:42:44,668] Trial 72 finished with value: 0.10926354016322501 and parameters: {'model_name': 'VAE', 'batch_size': 399, 'iterations': 2, 'learning_rate': 0.00459348968203581, 'p_miss': 0.18384707972100683}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:22,669] Trial 73 finished with value: 0.12155190125250066 and parameters: {'model_name': 'VAE', 'batch_size': 409, 'iterations': 2, 'learning_rate': 0.006122958973740496, 'p_miss': 0.1480575456652425}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:28,733] Trial 25 finished with value: 0.2021095818656478 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'ascending'}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:29,058] Trial 74 finished with value: 0.3379025433274768 and parameters: {'model_name': 'GAIN', 'batch_size': 427, 'hint_rate': 0.022782617994362098, 'alpha': 49, 'iterations': 1, 'learning_rate': 0.0037329446540082935, 'p_miss': 0.1656515767110013}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:29,303] Trial 75 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:46,981] Trial 77 finished with value: 0.11009849749274363 and parameters: {'model_name': 'VAE', 'batch_size': 460, 'iterations': 2, 'learning_rate': 0.0018370863565897694, 'p_miss': 0.18591508876435953}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:43:55,663] Trial 76 finished with value: 0.11130302639587093 and parameters: {'model_name': 'VAE', 'batch_size': 424, 'iterations': 4, 'learning_rate': 0.001861357081882201, 'p_miss': 0.189680466373125}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:44:03,603] Trial 78 finished with value: 0.1109830370531882 and parameters: {'model_name': 'VAE', 'batch_size': 428, 'iterations': 2, 'learning_rate': 0.0013985027716590097, 'p_miss': 0.2114655109518174}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:44:13,599] Trial 79 finished with value: 0.11033059099260838 and parameters: {'model_name': 'VAE', 'batch_size': 489, 'iterations': 2, 'learning_rate': 0.0014461975102647874, 'p_miss': 0.21646673611431405}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:44:14,242] Trial 80 finished with value: 0.11524895399799664 and parameters: {'model_name': 'VAE', 'batch_size': 265, 'iterations': 1, 'learning_rate': 0.0013605694525989128, 'p_miss': 0.21492637420886299}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:44:23,267] Trial 82 finished with value: 0.20637390447332313 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2355, 'weights': 'uniform'}. Best is trial 71 with value: 0.10789945061154911.
running
[I 2024-11-08 11:44:25,955] Trial 81 finished with value: 0.10773914501559063 and parameters: {'model_name': 'VAE', 'batch_size': 251, 'iterations': 1, 'learning_rate': 0.0045281064057831515, 'p_miss': 0.2342975586099721}. Best is trial 81 with value: 0.10773914501559063.
running
[I 2024-11-08 11:44:36,260] Trial 84 finished with value: 0.11091299155064671 and parameters: {'model_name': 'VAE', 'batch_size': 149, 'iterations': 1, 'learning_rate': 0.003885164694320769, 'p_miss': 0.2396766650276843}. Best is trial 81 with value: 0.10773914501559063.
running
[I 2024-11-08 11:44:36,661] Trial 85 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 81 with value: 0.10773914501559063.
running
[I 2024-11-08 11:44:45,590] Trial 83 finished with value: 0.10506140738206501 and parameters: {'model_name': 'VAE', 'batch_size': 985, 'iterations': 2, 'learning_rate': 0.004324270884024597, 'p_miss': 0.23791570246505414}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 11:44:58,862] Trial 86 finished with value: 0.1066228144934314 and parameters: {'model_name': 'VAE', 'batch_size': 988, 'iterations': 2, 'learning_rate': 0.0056869519036725595, 'p_miss': 0.23222892390375818}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 11:45:01,197] Trial 87 finished with value: 0.11325139238600698 and parameters: {'model_name': 'VAE', 'batch_size': 51, 'iterations': 2, 'learning_rate': 0.005732717505943606, 'p_miss': 0.23218950550369855}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 11:52:08,126] Trial 20 finished with value: 0.1988951514461822 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'arabic'}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:04:04,969] Trial 3 finished with value: 0.19856455229258446 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'random'}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:04:47,310] Trial 91 finished with value: 0.11142071360935848 and parameters: {'model_name': 'VAE', 'batch_size': 224, 'iterations': 5, 'learning_rate': 0.0033302907244027085, 'p_miss': 0.26005268796587644}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:06:49,425] Trial 48 finished with value: 0.1997716916498642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'roman'}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:07:05,433] Trial 93 finished with value: 0.10643587623272573 and parameters: {'model_name': 'VAE', 'batch_size': 665, 'iterations': 1, 'learning_rate': 0.00954032824670121, 'p_miss': 0.26263363621310304}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:22:03,476] Trial 92 finished with value: 0.20819590712897415 and parameters: {'model_name': 'VAE', 'batch_size': 671, 'iterations': 256, 'learning_rate': 0.010832973166102627, 'p_miss': 0.2577050810889775}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:22:10,009] Trial 95 finished with value: 0.3242015372574519 and parameters: {'model_name': 'GAIN', 'batch_size': 270, 'hint_rate': 0.4350277462461154, 'alpha': 3, 'iterations': 1, 'learning_rate': 0.01916281568755368, 'p_miss': 0.2943583292333235}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:22:54,280] Trial 96 finished with value: 0.12544337047561913 and parameters: {'model_name': 'VAE', 'batch_size': 658, 'iterations': 3, 'learning_rate': 0.00605049332205803, 'p_miss': 0.25355865480747636}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:23:15,236] Trial 97 finished with value: 0.10633612881915773 and parameters: {'model_name': 'VAE', 'batch_size': 317, 'iterations': 1, 'learning_rate': 0.004358838081549938, 'p_miss': 0.14575369905417998}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:23:27,273] Trial 98 finished with value: 0.10956606634187604 and parameters: {'model_name': 'VAE', 'batch_size': 959, 'iterations': 1, 'learning_rate': 0.004568873386244015, 'p_miss': 0.14782827036925253}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:23:40,450] Trial 99 finished with value: 0.1072761990928854 and parameters: {'model_name': 'VAE', 'batch_size': 926, 'iterations': 1, 'learning_rate': 0.004598937672951107, 'p_miss': 0.14860705966949705}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:42:34,886] Trial 89 finished with value: 0.20866426103846408 and parameters: {'model_name': 'VAE', 'batch_size': 273, 'iterations': 988, 'learning_rate': 0.0031523042652316013, 'p_miss': 0.2697060408189572}. Best is trial 83 with value: 0.10506140738206501.
running
[I 2024-11-08 12:42:52,982] Trial 101 finished with value: 0.10420603899174012 and parameters: {'model_name': 'VAE', 'batch_size': 632, 'iterations': 1, 'learning_rate': 0.00820024126056738, 'p_miss': 0.1168871480941079}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:43:02,073] Trial 102 finished with value: 0.20692759330599758 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1957, 'weights': 'uniform'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:43:20,258] Trial 103 finished with value: 0.10597075880036473 and parameters: {'model_name': 'VAE', 'batch_size': 598, 'iterations': 1, 'learning_rate': 0.00791425178414196, 'p_miss': 0.11749184235224816}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:43:38,307] Trial 104 finished with value: 0.11630651226513819 and parameters: {'model_name': 'VAE', 'batch_size': 614, 'iterations': 1, 'learning_rate': 0.01734654879594546, 'p_miss': 0.11206305370006522}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:43:55,237] Trial 105 finished with value: 0.10502494950678398 and parameters: {'model_name': 'VAE', 'batch_size': 601, 'iterations': 1, 'learning_rate': 0.008556481740386606, 'p_miss': 0.12082126803076632}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:44:07,613] Trial 106 finished with value: 0.10825929420450124 and parameters: {'model_name': 'VAE', 'batch_size': 979, 'iterations': 1, 'learning_rate': 0.008423487477130641, 'p_miss': 0.11819659340159447}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 12:44:25,510] Trial 107 finished with value: 0.10735282350215984 and parameters: {'model_name': 'VAE', 'batch_size': 572, 'iterations': 1, 'learning_rate': 0.009420799485000417, 'p_miss': 0.09783391851689442}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:07:58,962] Trial 94 finished with value: 0.20877666661868752 and parameters: {'model_name': 'VAE', 'batch_size': 670, 'iterations': 887, 'learning_rate': 0.015843399068092987, 'p_miss': 0.2990317500764506}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:08:11,152] Trial 109 finished with value: 0.10794459952987319 and parameters: {'model_name': 'VAE', 'batch_size': 994, 'iterations': 1, 'learning_rate': 0.008315509565002535, 'p_miss': 0.1363986351311461}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:08:27,627] Trial 110 finished with value: 0.1099136156884208 and parameters: {'model_name': 'VAE', 'batch_size': 613, 'iterations': 1, 'learning_rate': 0.012266293858015696, 'p_miss': 0.09352510412200556}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:09:05,890] Trial 111 finished with value: 0.13040174204739652 and parameters: {'model_name': 'VAE', 'batch_size': 153, 'iterations': 3, 'learning_rate': 0.007178518420429136, 'p_miss': 0.10421394196387138}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:09:07,645] Trial 112 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:21:51,916] Trial 113 finished with value: 0.20875954861818885 and parameters: {'model_name': 'VAE', 'batch_size': 708, 'iterations': 130, 'learning_rate': 0.009621569398366864, 'p_miss': 0.14057242352919833}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:22:14,939] Trial 114 finished with value: 0.2174485739183106 and parameters: {'model_name': 'VAE', 'batch_size': 20, 'iterations': 3, 'learning_rate': 0.026185422669981112, 'p_miss': 0.12470872742647138}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 13:22:33,344] Trial 115 finished with value: 0.109334422760348 and parameters: {'model_name': 'VAE', 'batch_size': 549, 'iterations': 1, 'learning_rate': 0.004702508355567275, 'p_miss': 0.09186170578309724}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 14:44:02,953] Trial 41 finished with value: 0.23915701799774491 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 5171, 'learning_rate': 0.00017199083960720007, 'p_miss': 0.2970541304569298}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 14:44:38,755] Trial 117 finished with value: 0.11557067575926774 and parameters: {'model_name': 'VAE', 'batch_size': 549, 'iterations': 2, 'learning_rate': 0.007113464188921718, 'p_miss': 0.2302147565755601}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 14:45:21,140] Trial 118 finished with value: 0.20500436917550932 and parameters: {'model_name': 'VAE', 'batch_size': 781, 'iterations': 3, 'learning_rate': 0.013891259653252365, 'p_miss': 0.12372176054598823}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 14:45:36,344] Trial 119 finished with value: 0.11225652112555776 and parameters: {'model_name': 'VAE', 'batch_size': 552, 'iterations': 1, 'learning_rate': 0.0028444766507850034, 'p_miss': 0.10309594158179239}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:06:09,625] Trial 42 finished with value: 0.23890821062458195 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 5540, 'learning_rate': 0.00013544733506270403, 'p_miss': 0.28769120058210207}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:06:52,157] Trial 121 finished with value: 0.18294848248769624 and parameters: {'model_name': 'VAE', 'batch_size': 334, 'iterations': 2, 'learning_rate': 0.0096308905818568, 'p_miss': 0.27734816234512155}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:07:01,628] Trial 122 finished with value: 0.20134806053815119 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5586, 'weights': 'uniform'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:07:16,594] Trial 123 finished with value: 0.1068205254574918 and parameters: {'model_name': 'VAE', 'batch_size': 862, 'iterations': 1, 'learning_rate': 0.005494825672463838, 'p_miss': 0.2455075583397834}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:07:31,437] Trial 124 finished with value: 0.10618461341653714 and parameters: {'model_name': 'VAE', 'batch_size': 815, 'iterations': 1, 'learning_rate': 0.0049867016694266535, 'p_miss': 0.07406340356577554}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:07:39,226] Trial 125 finished with value: 0.3517764828023949 and parameters: {'model_name': 'GAIN', 'batch_size': 799, 'hint_rate': 0.435201205948909, 'alpha': 64, 'iterations': 1, 'learning_rate': 0.005715081878107559, 'p_miss': 0.07688089167223827}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:07:55,560] Trial 126 finished with value: 0.1119704918612134 and parameters: {'model_name': 'VAE', 'batch_size': 783, 'iterations': 1, 'learning_rate': 0.004853646579662392, 'p_miss': 0.2468224145334032}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:12:33,922] Trial 127 finished with value: 0.20819261519545038 and parameters: {'model_name': 'VAE', 'batch_size': 355, 'iterations': 48, 'learning_rate': 0.007862266319933746, 'p_miss': 0.15276155621693133}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:12:48,364] Trial 128 finished with value: 0.11164373492015083 and parameters: {'model_name': 'VAE', 'batch_size': 833, 'iterations': 1, 'learning_rate': 0.003991610002259975, 'p_miss': 0.11217453366160629}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:13:12,392] Trial 129 finished with value: 0.10493895682585055 and parameters: {'model_name': 'VAE', 'batch_size': 996, 'iterations': 2, 'learning_rate': 0.005535035945858071, 'p_miss': 0.2673075468659123}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:13:39,220] Trial 130 finished with value: 0.10784870223617102 and parameters: {'model_name': 'VAE', 'batch_size': 900, 'iterations': 2, 'learning_rate': 0.006458537564269541, 'p_miss': 0.264549281669473}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:14:12,557] Trial 131 finished with value: 0.11818155131540498 and parameters: {'model_name': 'VAE', 'batch_size': 995, 'iterations': 3, 'learning_rate': 0.009096733257707079, 'p_miss': 0.04278504962072926}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:14:46,585] Trial 132 finished with value: 0.11181831275661502 and parameters: {'model_name': 'VAE', 'batch_size': 506, 'iterations': 2, 'learning_rate': 0.005865141005238334, 'p_miss': 0.2716866706905291}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:15:42,060] Trial 133 finished with value: 0.23613100929579725 and parameters: {'model_name': 'VAE', 'batch_size': 693, 'iterations': 4, 'learning_rate': 0.012049170446316355, 'p_miss': 0.24703035094208983}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:16:19,031] Trial 134 finished with value: 0.10648302671903484 and parameters: {'model_name': 'VAE', 'batch_size': 714, 'iterations': 3, 'learning_rate': 0.002455235473788762, 'p_miss': 0.0746804581444104}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:16:20,852] Trial 135 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:17:16,898] Trial 136 finished with value: 0.10969513323251687 and parameters: {'model_name': 'VAE', 'batch_size': 622, 'iterations': 5, 'learning_rate': 0.0024731679893090497, 'p_miss': 0.07016366842724996}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:17:43,040] Trial 137 finished with value: 0.10589771993481867 and parameters: {'model_name': 'VAE', 'batch_size': 799, 'iterations': 2, 'learning_rate': 0.005320946161535347, 'p_miss': 0.0920699856674399}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:18:13,074] Trial 138 finished with value: 0.10504298117590109 and parameters: {'model_name': 'VAE', 'batch_size': 775, 'iterations': 2, 'learning_rate': 0.0033367562116160252, 'p_miss': 0.080800932524686}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:19:14,684] Trial 139 finished with value: 0.11290102068389993 and parameters: {'model_name': 'VAE', 'batch_size': 738, 'iterations': 5, 'learning_rate': 0.0033787982491979606, 'p_miss': 0.08536160227467789}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:20:07,933] Trial 140 finished with value: 0.134500639653437 and parameters: {'model_name': 'VAE', 'batch_size': 456, 'iterations': 3, 'learning_rate': 0.005468789589052737, 'p_miss': 0.07522164710153051}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:25:47,044] Trial 45 finished with value: 0.2488829076928233 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 5959, 'learning_rate': 0.0001142776144238378, 'p_miss': 0.2789763392475108}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:26:41,101] Trial 142 finished with value: 0.10655800582693482 and parameters: {'model_name': 'VAE', 'batch_size': 760, 'iterations': 4, 'learning_rate': 0.00290132335591588, 'p_miss': 0.08509205874828832}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:27:29,113] Trial 143 finished with value: 0.10794748465036715 and parameters: {'model_name': 'VAE', 'batch_size': 752, 'iterations': 4, 'learning_rate': 0.0021447078741896513, 'p_miss': 0.05207471220296342}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:28:45,325] Trial 144 finished with value: 0.11767253933911678 and parameters: {'model_name': 'VAE', 'batch_size': 352, 'iterations': 8, 'learning_rate': 0.00284985105835797, 'p_miss': 0.08674088714288886}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:28:54,931] Trial 145 finished with value: 0.3537159309451404 and parameters: {'model_name': 'GAIN', 'batch_size': 487, 'hint_rate': 0.6733551857841396, 'alpha': 100, 'iterations': 2, 'learning_rate': 0.003920595154633817, 'p_miss': 0.07858626113590138}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:29:35,914] Trial 146 finished with value: 0.11264717331615474 and parameters: {'model_name': 'VAE', 'batch_size': 803, 'iterations': 3, 'learning_rate': 0.006846070958535961, 'p_miss': 0.2258038746887193}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:29:57,575] Trial 147 finished with value: 0.10795206062483582 and parameters: {'model_name': 'VAE', 'batch_size': 65, 'iterations': 2, 'learning_rate': 0.005194039056094917, 'p_miss': 0.06666964161828216}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:31:08,967] Trial 148 finished with value: 0.11918294462777386 and parameters: {'model_name': 'VAE', 'batch_size': 666, 'iterations': 6, 'learning_rate': 0.003500525541358583, 'p_miss': 0.11373642735722826}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:31:46,177] Trial 149 finished with value: 0.1062433917510726 and parameters: {'model_name': 'VAE', 'batch_size': 891, 'iterations': 3, 'learning_rate': 0.002973248908227321, 'p_miss': 0.0981735421027746}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:43:31,523] Trial 100 finished with value: 0.20801166336229512 and parameters: {'model_name': 'VAE', 'batch_size': 656, 'iterations': 2921, 'learning_rate': 0.00854615796102683, 'p_miss': 0.11660495671393925}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:44:19,107] Trial 151 finished with value: 0.10617924272916354 and parameters: {'model_name': 'VAE', 'batch_size': 531, 'iterations': 3, 'learning_rate': 0.0028221657389553624, 'p_miss': 0.09940308507726146}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:44:32,303] Trial 152 finished with value: 0.20323587979201224 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4141, 'weights': 'distance'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:45:20,978] Trial 153 finished with value: 0.10820425231090436 and parameters: {'model_name': 'VAE', 'batch_size': 409, 'iterations': 4, 'learning_rate': 0.0028919333469401226, 'p_miss': 0.09837518030511953}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:46:00,257] Trial 154 finished with value: 0.10860072170875243 and parameters: {'model_name': 'VAE', 'batch_size': 511, 'iterations': 5, 'learning_rate': 0.002110117421843314, 'p_miss': 0.09240316200255429}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:47:05,546] Trial 155 finished with value: 0.122011000725982 and parameters: {'model_name': 'VAE', 'batch_size': 588, 'iterations': 4, 'learning_rate': 0.004051713624565295, 'p_miss': 0.10579924147456937}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:47:43,760] Trial 156 finished with value: 0.10629188158149208 and parameters: {'model_name': 'VAE', 'batch_size': 853, 'iterations': 3, 'learning_rate': 0.0026639597124197725, 'p_miss': 0.08314458642415326}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:48:55,160] Trial 157 finished with value: 0.10973875209077563 and parameters: {'model_name': 'VAE', 'batch_size': 739, 'iterations': 6, 'learning_rate': 0.002559120652992555, 'p_miss': 0.08328002864304547}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:49:23,824] Trial 158 finished with value: 0.10864445907053955 and parameters: {'model_name': 'VAE', 'batch_size': 879, 'iterations': 3, 'learning_rate': 0.0019437012639452694, 'p_miss': 0.08744098231068806}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:50:09,369] Trial 159 finished with value: 0.10952399990309698 and parameters: {'model_name': 'VAE', 'batch_size': 616, 'iterations': 4, 'learning_rate': 0.0030802021615417407, 'p_miss': 0.07222612043030793}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:50:44,430] Trial 160 finished with value: 0.10728195361420634 and parameters: {'model_name': 'VAE', 'batch_size': 486, 'iterations': 2, 'learning_rate': 0.004228883359420116, 'p_miss': 0.13150107532486166}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:51:16,768] Trial 161 finished with value: 0.11588365888288836 and parameters: {'model_name': 'VAE', 'batch_size': 1000, 'iterations': 3, 'learning_rate': 0.0010508317521912482, 'p_miss': 0.0986157094287558}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:52:24,384] Trial 162 finished with value: 0.10776599553614052 and parameters: {'model_name': 'VAE', 'batch_size': 701, 'iterations': 6, 'learning_rate': 0.002490831775038644, 'p_miss': 0.07949653338268263}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:54:46,503] Trial 163 finished with value: 0.2089019353106905 and parameters: {'model_name': 'VAE', 'batch_size': 382, 'iterations': 18, 'learning_rate': 0.007579352276282808, 'p_miss': 0.10870113056911535}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:55:33,752] Trial 164 finished with value: 0.11053427923271011 and parameters: {'model_name': 'VAE', 'batch_size': 315, 'iterations': 9, 'learning_rate': 0.0035229460052482236, 'p_miss': 0.12066111721049297}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:58:22,552] Trial 165 finished with value: 0.18701780439333923 and parameters: {'model_name': 'VAE', 'batch_size': 857, 'iterations': 24, 'learning_rate': 0.002780409202198721, 'p_miss': 0.05813139160244704}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:59:03,460] Trial 15 finished with value: 0.2091882438071738 and parameters: {'model_name': 'VAE', 'batch_size': 408, 'iterations': 5633, 'learning_rate': 0.00010234979326698242, 'p_miss': 0.07616405094397825}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:59:13,055] Trial 166 finished with value: 0.14219847889234322 and parameters: {'model_name': 'VAE', 'batch_size': 573, 'iterations': 3, 'learning_rate': 0.006752475809304681, 'p_miss': 0.28210744603983307}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 15:59:38,491] Trial 168 finished with value: 0.10693710351249627 and parameters: {'model_name': 'VAE', 'batch_size': 883, 'iterations': 2, 'learning_rate': 0.005048095092737333, 'p_miss': 0.08806324480158272}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:00:01,710] Trial 169 finished with value: 0.10915281083179458 and parameters: {'model_name': 'VAE', 'batch_size': 687, 'iterations': 2, 'learning_rate': 0.003187581503811325, 'p_miss': 0.09519062671612223}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:00:57,374] Trial 167 finished with value: 0.2052384302068459 and parameters: {'model_name': 'VAE', 'batch_size': 871, 'iterations': 12, 'learning_rate': 0.010435307133766324, 'p_miss': 0.09035328238949028}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:00:57,864] Trial 171 finished with value: 0.36350816245106043 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:01:09,943] Trial 170 finished with value: 0.24139456811480292 and parameters: {'model_name': 'VAE', 'batch_size': 786, 'iterations': 5, 'learning_rate': 0.010487734548276716, 'p_miss': 0.10127230479470746}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:01:51,144] Trial 172 finished with value: 0.10804529779338426 and parameters: {'model_name': 'VAE', 'batch_size': 783, 'iterations': 4, 'learning_rate': 0.003601793792829718, 'p_miss': 0.14059476812408508}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:02:05,853] Trial 173 finished with value: 0.11615612736679759 and parameters: {'model_name': 'VAE', 'batch_size': 586, 'iterations': 4, 'learning_rate': 0.004157652724945319, 'p_miss': 0.12825622122374375}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:02:30,275] Trial 174 finished with value: 0.2134975213432771 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 1, 'imputation_order': 'arabic'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:02:41,779] Trial 175 finished with value: 0.2134975213432771 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 1, 'imputation_order': 'arabic'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:02:56,051] Trial 176 finished with value: 0.10607373327261826 and parameters: {'model_name': 'VAE', 'batch_size': 877, 'iterations': 2, 'learning_rate': 0.005080773931712227, 'p_miss': 0.06709461871462107}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:03:15,963] Trial 177 finished with value: 0.1048368873144098 and parameters: {'model_name': 'VAE', 'batch_size': 994, 'iterations': 3, 'learning_rate': 0.005124070373289438, 'p_miss': 0.2514925478474825}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:03:31,219] Trial 178 finished with value: 0.10738509702726248 and parameters: {'model_name': 'VAE', 'batch_size': 966, 'iterations': 3, 'learning_rate': 0.006371984323169274, 'p_miss': 0.06462535514874798}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:03:59,299] Trial 179 finished with value: 0.12285953732962415 and parameters: {'model_name': 'VAE', 'batch_size': 680, 'iterations': 3, 'learning_rate': 0.006391825387321233, 'p_miss': 0.06660958434569922}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:04:13,402] Trial 180 finished with value: 0.10898700205615763 and parameters: {'model_name': 'VAE', 'batch_size': 677, 'iterations': 3, 'learning_rate': 0.004991614227414169, 'p_miss': 0.25529232830641807}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:04:25,384] Trial 182 finished with value: 0.10884253294861031 and parameters: {'model_name': 'VAE', 'batch_size': 12, 'iterations': 2, 'learning_rate': 0.007910876272391738, 'p_miss': 0.05257441480458388}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:04:37,786] Trial 181 finished with value: 0.11024958242031346 and parameters: {'model_name': 'VAE', 'batch_size': 500, 'iterations': 3, 'learning_rate': 0.00457219245065731, 'p_miss': 0.08031455957719455}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:04:47,779] Trial 184 finished with value: 0.32376170773477175 and parameters: {'model_name': 'GAIN', 'batch_size': 983, 'hint_rate': 0.2567265094149638, 'alpha': 36, 'iterations': 2, 'learning_rate': 0.0016814723949377366, 'p_miss': 0.2682225007621466}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:05:51,381] Trial 185 finished with value: 0.10860424042222871 and parameters: {'model_name': 'VAE', 'batch_size': 781, 'iterations': 7, 'learning_rate': 0.002275963302183043, 'p_miss': 0.07452843837306469}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:06:14,631] Trial 186 finished with value: 0.10623447960952181 and parameters: {'model_name': 'VAE', 'batch_size': 996, 'iterations': 2, 'learning_rate': 0.005496081843888821, 'p_miss': 0.2609519550428729}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:06:40,369] Trial 187 finished with value: 0.10874979889268503 and parameters: {'model_name': 'VAE', 'batch_size': 861, 'iterations': 2, 'learning_rate': 0.0038106173348266773, 'p_miss': 0.26546396930586824}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:14:45,927] Trial 33 finished with value: 0.20823385618532594 and parameters: {'model_name': 'VAE', 'batch_size': 969, 'iterations': 4387, 'learning_rate': 0.0002760541624641248, 'p_miss': 0.2962659399627091}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:15:32,202] Trial 183 finished with value: 0.2084878912615943 and parameters: {'model_name': 'VAE', 'batch_size': 480, 'iterations': 139, 'learning_rate': 0.0045453159640444895, 'p_miss': 0.08039370382667246}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:15:46,493] Trial 189 finished with value: 0.14185267142793356 and parameters: {'model_name': 'VAE', 'batch_size': 628, 'iterations': 4, 'learning_rate': 0.005405965100896944, 'p_miss': 0.25008909647785793}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:15:54,883] Trial 191 finished with value: 0.20725612582408215 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1750, 'weights': 'uniform'}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:16:37,725] Trial 190 finished with value: 0.15539861643332678 and parameters: {'model_name': 'VAE', 'batch_size': 561, 'iterations': 4, 'learning_rate': 0.005256988340765178, 'p_miss': 0.27607082937087646}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:17:00,823] Trial 192 finished with value: 0.11311713295856299 and parameters: {'model_name': 'VAE', 'batch_size': 744, 'iterations': 5, 'learning_rate': 0.0031389472907535857, 'p_miss': 0.25953716918474923}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:17:03,285] Trial 193 finished with value: 0.10711619149769809 and parameters: {'model_name': 'VAE', 'batch_size': 761, 'iterations': 2, 'learning_rate': 0.0031429581056355146, 'p_miss': 0.25816392883054257}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:17:26,835] Trial 194 finished with value: 0.10883306967699473 and parameters: {'model_name': 'VAE', 'batch_size': 811, 'iterations': 2, 'learning_rate': 0.0026705003293452973, 'p_miss': 0.10722707288891557}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:17:51,206] Trial 196 finished with value: 0.10720754564422363 and parameters: {'model_name': 'VAE', 'batch_size': 962, 'iterations': 2, 'learning_rate': 0.0076131244424751075, 'p_miss': 0.24403582367356166}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:18:05,169] Trial 197 finished with value: 0.10665552187763772 and parameters: {'model_name': 'VAE', 'batch_size': 883, 'iterations': 1, 'learning_rate': 0.005918941440975446, 'p_miss': 0.24124062305185595}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:18:38,141] Trial 198 finished with value: 0.1136019974690285 and parameters: {'model_name': 'VAE', 'batch_size': 997, 'iterations': 3, 'learning_rate': 0.00875578372419443, 'p_miss': 0.07192767483537676}. Best is trial 101 with value: 0.10420603899174012.
running
[I 2024-11-08 16:20:39,809] Trial 188 finished with value: 0.20873394555053001 and parameters: {'model_name': 'VAE', 'batch_size': 614, 'iterations': 169, 'learning_rate': 0.005487778077673848, 'p_miss': 0.27305892789448266}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 16:42:15,548] Trial 199 finished with value: 0.20959875392107427 and parameters: {'model_name': 'VAE', 'batch_size': 27, 'iterations': 454, 'learning_rate': 0.003942540261119614, 'p_miss': 0.1637966189886218}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 17:39:16,114] Trial 90 finished with value: 0.2091748424773691 and parameters: {'model_name': 'VAE', 'batch_size': 275, 'iterations': 6152, 'learning_rate': 0.0034440638954469148, 'p_miss': 0.25795506198070284}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 17:43:20,348] Trial 47 finished with value: 0.20864072420809227 and parameters: {'model_name': 'VAE', 'batch_size': 814, 'iterations': 5482, 'learning_rate': 0.0001264248231461404, 'p_miss': 0.2702542845241817}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:01:56,801] Trial 32 finished with value: 0.21500973993219813 and parameters: {'model_name': 'VAE', 'batch_size': 741, 'iterations': 5633, 'learning_rate': 0.0984657402406767, 'p_miss': 0.2969457384699535}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:03:47,626] Trial 195 finished with value: 0.2084311100583763 and parameters: {'model_name': 'VAE', 'batch_size': 842, 'iterations': 1599, 'learning_rate': 0.007030563329251414, 'p_miss': 0.07077089148342687}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:03:58,571] Trial 44 finished with value: 0.24436462945856086 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 8580, 'learning_rate': 0.00010574949024782543, 'p_miss': 0.2870204353898418}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:07:15,481] Trial 43 finished with value: 0.23672187657751292 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 8870, 'learning_rate': 0.00012501344581195874, 'p_miss': 0.2842365883872091}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:13:42,233] Trial 88 finished with value: 0.20933749430493126 and parameters: {'model_name': 'VAE', 'batch_size': 60, 'iterations': 6821, 'learning_rate': 0.0057622182244354584, 'p_miss': 0.2589300512515196}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:22:52,782] Trial 108 finished with value: 0.20805516064446872 and parameters: {'model_name': 'VAE', 'batch_size': 654, 'iterations': 5725, 'learning_rate': 0.007608813929246921, 'p_miss': 0.10082349695473329}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:29:17,704] Trial 46 finished with value: 0.23400929096047401 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 9679, 'learning_rate': 0.00011506976598964093, 'p_miss': 0.29185406062770514}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:36:29,214] Trial 116 finished with value: 0.20835227028260914 and parameters: {'model_name': 'VAE', 'batch_size': 536, 'iterations': 5735, 'learning_rate': 0.0069411412203701445, 'p_miss': 0.15558779821570362}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 18:46:38,355] Trial 34 finished with value: 0.20973715481887029 and parameters: {'model_name': 'VAE', 'batch_size': 427, 'iterations': 9850, 'learning_rate': 0.00010157352697159743, 'p_miss': 0.2996213508354203}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 19:02:53,242] Trial 120 finished with value: 0.2092344348177347 and parameters: {'model_name': 'VAE', 'batch_size': 320, 'iterations': 9675, 'learning_rate': 0.005580449227397847, 'p_miss': 0.24619537366282532}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 19:05:40,295] Trial 141 finished with value: 0.20854622051171132 and parameters: {'model_name': 'VAE', 'batch_size': 773, 'iterations': 7984, 'learning_rate': 0.002773505378122652, 'p_miss': 0.08354093976217519}. Best is trial 101 with value: 0.10420603899174012.
[I 2024-11-08 19:06:14,042] Trial 150 finished with value: 0.2083890811824046 and parameters: {'model_name': 'VAE', 'batch_size': 609, 'iterations': 8168, 'learning_rate': 0.002886739861672013, 'p_miss': 0.10003633582837866}. Best is trial 101 with value: 0.10420603899174012.
fit
auto fit
auto transform
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
dtype: int64
0.10420603899174012
{'model_name': 'VAE', 'batch_size': 632, 'iterations': 1, 'learning_rate': 0.00820024126056738, 'p_miss': 0.1168871480941079}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a0e80> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  1
Best f1_score score: 0.5338896651043586
Generation:   4%|▍         | 1/25 [01:14<29:50, 74.59s/it]Generation:  2
Best f1_score score: 0.5338896651043586
Generation:   8%|▊         | 2/25 [03:36<43:40, 113.94s/it]Generation:  3
Best f1_score score: 0.5338896651043586
Generation:  12%|█▏        | 3/25 [05:00<36:49, 100.43s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467ffd6f0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  4
Best f1_score score: 0.5338896651043586
Generation:  16%|█▌        | 4/25 [05:13<23:08, 66.14s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467477fa0> 
 shrinkage not supported with 'svd' solver. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/discriminant_analysis.py", line 629, in fit
    raise NotImplementedError("shrinkage not supported with 'svd' solver.")
NotImplementedError: shrinkage not supported with 'svd' solver.

Generation:  5
Best f1_score score: 0.5338896651043586
Generation:  20%|██        | 5/25 [06:24<22:33, 67.68s/it]Generation:  6
Best f1_score score: 0.5338896651043586
Generation:  24%|██▍       | 6/25 [07:16<19:42, 62.25s/it]Generation:  7
Best f1_score score: 0.5338896651043586
Generation:  28%|██▊       | 7/25 [07:45<15:27, 51.51s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467aa5750> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a3bb0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  8
Best f1_score score: 0.5338896651043586
Generation:  32%|███▏      | 8/25 [08:20<13:04, 46.12s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465835c90> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467963eb0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554658ccdc0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  9
Best f1_score score: 0.5338896651043586
Generation:  36%|███▌      | 9/25 [08:58<11:37, 43.56s/it]Generation:  10
Best f1_score score: 0.5338896651043586
Generation:  40%|████      | 10/25 [09:42<10:57, 43.80s/it]Generation:  11
Best f1_score score: 0.5338896651043586
Generation:  44%|████▍     | 11/25 [10:18<09:38, 41.35s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467a2f070> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  12
Best f1_score score: 0.5338896651043586
Generation:  48%|████▊     | 12/25 [10:45<08:00, 36.99s/it]Generation:  13
Best f1_score score: 0.5338896651043586
Generation:  52%|█████▏    | 13/25 [11:15<06:59, 34.98s/it]Generation:  14
Best f1_score score: 0.5338896651043586
Generation:  56%|█████▌    | 14/25 [12:27<08:28, 46.23s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465877be0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  15
Best f1_score score: 0.5338896651043586
Generation:  60%|██████    | 15/25 [13:07<07:21, 44.18s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465173970> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467accc40> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  16
Best f1_score score: 0.5338896651043586
Generation:  64%|██████▍   | 16/25 [13:50<06:34, 43.78s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554652630d0> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  17
Best f1_score score: 0.5338896651043586
Generation:  68%|██████▊   | 17/25 [14:28<05:36, 42.09s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467bc6530> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  18
Best f1_score score: 0.5338896651043586
Generation:  72%|███████▏  | 18/25 [15:05<04:44, 40.62s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f8310> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  19
Best f1_score score: 0.5338896651043586
Generation:  76%|███████▌  | 19/25 [15:36<03:46, 37.68s/it]Generation:  20
Best f1_score score: 0.5338896651043586
Generation:  80%|████████  | 20/25 [16:28<03:30, 42.01s/it]Generation:  21
Best f1_score score: 0.5338896651043586
Generation:  84%|████████▍ | 21/25 [17:03<02:40, 40.06s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546502ba00> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155477284520> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  22
Best f1_score score: 0.5338896651043586
Generation:  88%|████████▊ | 22/25 [17:36<01:53, 37.80s/it]Generation:  23
Best f1_score score: 0.5338896651043586
Generation:  92%|█████████▏| 23/25 [18:05<01:10, 35.13s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554652eb820> 
 Argument 'metric' has incorrect type (expected str, got numpy.str_) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_classification.py", line 259, in predict
    probabilities = self.predict_proba(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_classification.py", line 343, in predict_proba
    probabilities = ArgKminClassMode.compute(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 598, in compute
    return ArgKminClassMode32.compute(
TypeError: Argument 'metric' has incorrect type (expected str, got numpy.str_)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f07eb0> 
 Argument 'metric' has incorrect type (expected str, got numpy.str_) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in cross_val_score_objective
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 31, in <listcomp>
    this_fold_scores = [sklearn.metrics.get_scorer(scorer)(this_fold_pipeline, X_test, y_test) for scorer in scorers]
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 279, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 371, in _score
    y_pred = method_caller(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 601, in predict
    return self.steps[-1][1].predict(Xt, **params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_classification.py", line 259, in predict
    probabilities = self.predict_proba(X)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neighbors/_classification.py", line 343, in predict_proba
    probabilities = ArgKminClassMode.compute(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/metrics/_pairwise_distances_reduction/_dispatcher.py", line 598, in compute
    return ArgKminClassMode32.compute(
TypeError: Argument 'metric' has incorrect type (expected str, got numpy.str_)

Generation:  24
Best f1_score score: 0.5338896651043586
Generation:  96%|█████████▌| 24/25 [19:14<00:45, 45.33s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465ad3a30> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  25
Best f1_score score: 0.5338896651043586
Generation: 100%|██████████| 25/25 [20:09<00:00, 48.28s/it]Generation: 100%|██████████| 25/25 [20:13<00:00, 48.55s/it]
2024-11-08 19:26:45,399 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:45581' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-e36ee650668bc5d6361b677967e19b49', 'ndarray-d8b8a177c15b9d764d6c1db847317b9d'} (stimulus_id='handle-worker-cleanup-1731122805.3996322')
Fitted
Pipeline(steps=[('mlpclassifier',
                 MLPClassifier(activation='logistic', alpha=0.0032116715983,
                               early_stopping=True, hidden_layer_sizes=[241],
                               learning_rate='adaptive',
                               learning_rate_init=0.0004075160914,
                               n_iter_no_change=32))])
score start
train score: {'auroc': 0.5594207379568745, 'accuracy': 0.5464527027027027, 'balanced_accuracy': 0.546498491827288, 'logloss': 0.6879271708846332, 'f1': 0.5443830271384068}
original test score: {'auroc': 0.9943261401134771, 'accuracy': 0.8743243243243243, 'balanced_accuracy': 0.8744884486640772, 'logloss': 0.6761570011586707, 'f1': 0.87247975185249}
imputed test score: {'auroc': 0.5462409536905655, 'accuracy': 0.529054054054054, 'balanced_accuracy': 0.5291216748021819, 'logloss': 0.6896973592102847, 'f1': 0.5279055005535289}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x155435014610>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd10f0> 

Generation:  1
Best f1_score score: 0.896939422731051
Generation:   4%|▍         | 1/25 [10:02<4:00:59, 602.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d1a2f0> 
 Input X contains NaN.
AdaBoostClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py", line 133, in fit
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
AdaBoostClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d54d30> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d75390> 

Generation:  2
Best f1_score score: 0.914354259680467
Generation:   8%|▊         | 2/25 [20:07<3:51:25, 603.73s/it]Generation:  3
Best f1_score score: 0.914354259680467
Generation:  12%|█▏        | 3/25 [20:41<2:06:04, 343.86s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545ff41f90> 
 Input X contains NaN.
LinearDiscriminantAnalysis does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/discriminant_analysis.py", line 589, in fit
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LinearDiscriminantAnalysis does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  4
Best f1_score score: 0.914354259680467
Generation:  16%|█▌        | 4/25 [21:09<1:16:43, 219.20s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554745bec50> 
 Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 263, in fit
    return self._partial_fit(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 423, in _partial_fit
    X, y = self._validate_data(X, y, reset=first_call)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  5
Best f1_score score: 0.914354259680467
Generation:  20%|██        | 5/25 [23:24<1:02:56, 188.84s/it]Generation:  6
Best f1_score score: 0.914354259680467
Generation:  24%|██▍       | 6/25 [24:48<48:28, 153.09s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15540c4f8a30> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155456f953c0> 

Generation:  7
Best f1_score score: 0.9150286551045834
Generation:  28%|██▊       | 7/25 [34:53<1:30:17, 300.99s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fb96440> 
 Input X contains NaN.
MLPClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1096, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  8
Best f1_score score: 0.9155209210165893
Generation:  32%|███▏      | 8/25 [37:46<1:13:39, 260.00s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d3b4c0> 

Generation:  9
Best f1_score score: 0.9155358543052692
Generation:  36%|███▌      | 9/25 [47:51<1:38:05, 367.86s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d361a0> 

Generation:  10
Best f1_score score: 0.9157054730258569
Generation:  40%|████      | 10/25 [57:56<1:50:19, 441.29s/it]Generation:  11
Best f1_score score: 0.9157054730258569
Generation:  44%|████▍     | 11/25 [1:00:14<1:21:18, 348.45s/it]Generation:  12
Best f1_score score: 0.9157054730258569
Generation:  48%|████▊     | 12/25 [1:04:26<1:09:07, 319.08s/it]Generation:  13
Best f1_score score: 0.9157054730258569
Generation:  52%|█████▏    | 13/25 [1:05:35<48:39, 243.32s/it]  Generation:  14
Best f1_score score: 0.9157054730258569
Generation:  56%|█████▌    | 14/25 [1:06:03<32:38, 178.08s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd3310> 

Generation:  15
Best f1_score score: 0.9157054730258569
Generation:  60%|██████    | 15/25 [1:16:09<51:10, 307.08s/it]Generation:  16
Best f1_score score: 0.9157054730258569
Generation:  64%|██████▍   | 16/25 [1:22:10<48:31, 323.49s/it]Generation:  17
Best f1_score score: 0.9157054730258569
Generation:  68%|██████▊   | 17/25 [1:22:50<31:44, 238.05s/it]Generation:  18
Best f1_score score: 0.9157054730258569
Generation:  72%|███████▏  | 18/25 [1:23:20<20:29, 175.70s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155377ba13f0> 

Generation:  19
Best f1_score score: 0.9157054730258569
Generation:  76%|███████▌  | 19/25 [1:33:25<30:27, 304.65s/it]Generation:  20
Best f1_score score: 0.9157054730258569
Generation:  80%|████████  | 20/25 [1:33:52<18:26, 221.36s/it]Generation:  21
Best f1_score score: 0.9157054730258569
Generation:  84%|████████▍ | 21/25 [1:37:51<15:06, 226.51s/it]Generation:  22
Best f1_score score: 0.9157054730258569
Generation:  88%|████████▊ | 22/25 [1:38:20<08:21, 167.16s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545b7c83d0> 
 The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

Generation:  23
Best f1_score score: 0.9158741498350981
Generation:  92%|█████████▏| 23/25 [1:40:49<05:23, 161.79s/it]Generation:  24
Best f1_score score: 0.9158741498350981
Generation:  96%|█████████▌| 24/25 [1:43:04<02:33, 153.70s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545dc15930> 

Generation:  25
Best f1_score score: 0.9158741498350981
Generation: 100%|██████████| 25/25 [1:53:10<00:00, 289.46s/it]Generation: 100%|██████████| 25/25 [1:53:10<00:00, 271.62s/it]
2024-11-08 21:20:06,737 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:41613' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-956cece637a034ce759c28d1abc76afb', 'ndarray-d8b8a177c15b9d764d6c1db847317b9d'} (stimulus_id='handle-worker-cleanup-1731129606.7373118')
Fitted
Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('lineardiscriminantanalysis',
                 LinearDiscriminantAnalysis(shrinkage=0.5074674597356,
                                            solver='eigen'))])
transform worked
try transform
transform worked
score start
train score: {'auroc': 0.9746158120050272, 'accuracy': 0.9157094594594595, 'balanced_accuracy': 0.9157083937675282, 'logloss': 0.20490835128195484, 'f1': 0.9157090529934588}
test score: {'auroc': 0.9739608728284749, 'accuracy': 0.9155405405405406, 'balanced_accuracy': 0.9155522563043395, 'logloss': 0.20687463668864992, 'f1': 0.9155358746534117}
original test score: {'auroc': 0.9976734800465303, 'accuracy': 0.977027027027027, 'balanced_accuracy': 0.9770233327672257, 'logloss': 0.062660504088006, 'f1': 0.9770266494518719}
score end
1507
lvl
0.5
type
MCAR
num_run
2
class_full
finished
all finished
full run takes
11.100615097482999
hours
DONE
