Run: 2
/cm/local/apps/slurm/var/spool/job957856/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
starting loops
../data/r/189/189.pkl
        theta1    theta2    theta3    theta4    theta5    theta6    theta7  \
0    -0.015119  0.360741  0.469398  1.309675  0.988024 -0.025493  0.664071   
1     0.360478 -0.301395  0.629183 -1.440146 -0.741637 -1.196749 -1.038444   
2     1.563238 -1.294753  0.078987  1.432937  1.149136 -1.292140  1.562988   
3     0.199485  0.901157 -1.356304 -0.080525 -0.976628  0.829894 -0.855649   
4     0.659737  0.120552 -0.008756  0.648839  0.626832 -0.646539  1.318074   
...        ...       ...       ...       ...       ...       ...       ...   
8187  1.459523 -0.201551 -0.610721  1.424181  0.269273  1.172781 -0.509818   
8188  0.654980 -0.823516 -0.809246  0.408441 -1.368838  0.582222 -1.394697   
8189  0.103862  1.024329 -1.047221  0.280905 -0.181155 -0.651934 -1.241842   
8190 -1.109311 -0.027690 -1.448736 -0.648566 -0.462142  0.814971  1.100615   
8191  1.155010 -0.429331 -1.567260  0.883077 -1.203777 -0.126506  0.331042   

        theta8  
0     0.062763  
1    -0.717461  
2    -0.937731  
3     0.930630  
4    -0.899172  
...        ...  
8187 -0.686006  
8188 -0.057294  
8189  1.530220  
8190  1.337159  
8191 -1.327384  

[8192 rows x 8 columns]
<class 'pandas.core.frame.DataFrame'>
        theta1    theta2    theta3    theta4    theta5    theta6    theta7  \
7930  0.108179  0.564341 -1.127350  0.162126 -0.652018  0.229836 -0.704088   
1349 -1.467262 -0.517016 -1.038032  1.317828  0.908326  1.147639  0.358737   
4080 -0.743830  0.084709  0.676295  0.150865  1.139795  0.088262 -0.192145   
3850  1.342977  0.632445  0.400362  1.389721  0.664597  0.509910 -0.203616   
2927 -0.844696 -1.077894  1.096806 -0.659045 -0.164704  1.124389 -0.488116   
...        ...       ...       ...       ...       ...       ...       ...   
1095  1.504658 -1.261215  0.613916  0.184433 -1.445837  1.408608  1.102782   
4417 -0.182262  0.656169  0.883128 -0.503386  1.055302 -0.834552  1.202496   
1697  0.371469 -0.081697  1.384823  0.268939 -0.062316 -0.686823  0.965892   
5851 -1.080766 -1.093952 -0.707859  0.184049 -0.089452  0.096765  0.967920   
1696 -0.469338  1.268633  0.636738 -0.193448 -1.292754 -0.352762  0.848869   

        theta8  
7930  1.080599  
1349 -0.117773  
4080  1.365243  
3850  0.814675  
2927 -1.457958  
...        ...  
1095  0.501548  
4417 -0.328196  
1697 -0.808631  
5851 -0.095115  
1696  0.048365  

[6553 rows x 8 columns]
<class 'pandas.core.frame.DataFrame'>
             0         1         2         3         4         5         6  \
0     0.534510  0.679654  0.141121  0.551657  0.292441  0.573122  0.275871   
1     0.032905  0.335419  0.169554  0.919669  0.789169  0.865336  0.614224   
2     0.263239  0.526970  0.715274  0.548072  0.862856  0.528047  0.438849   
3     0.927657  0.701334  0.627436  0.942562  0.711579  0.662293  0.435198   
4     0.231124  0.156872  0.849134  0.290171  0.447575  0.857934  0.344626   
...        ...       ...       ...       ...       ...       ...       ...   
6548  0.979135  0.098514  0.695416  0.558761  0.039733  0.948425  0.851093   
6549  0.442036  0.708886  0.781115  0.339737  0.835958  0.234237  0.882838   
6550  0.618339  0.473997  0.940818  0.585670  0.480170  0.281271  0.807514   
6551  0.155962  0.151760  0.274657  0.558638  0.471531  0.530754  0.808160   
6552  0.350634  0.903855  0.702681  0.438431  0.088466  0.387631  0.770259   

             7  
0     0.844051  
1     0.462286  
2     0.934730  
3     0.759336  
4     0.035344  
...        ...  
6548  0.659583  
6549  0.395252  
6550  0.242200  
6551  0.469504  
6552  0.515212  

[6553 rows x 8 columns]
<class 'numpy.ndarray'>
             0         1         2         3         4         5         6  \
0     0.928996  0.896631  0.683231  0.575902  0.787714  0.882499  0.161174   
1     0.063602  0.206285  0.542937  0.131070  0.697760  0.922099  0.413562   
2     0.284939  0.349478  0.318258  0.129485  0.442931  0.502938  0.415060   
3     0.523064  0.914859  0.336865  0.491720  0.744138  0.035872  0.849306   
4     0.291066  0.417925  0.515690  0.749585  0.943758  0.709411  0.764687   
...        ...       ...       ...       ...       ...       ...       ...   
1634  0.146748  0.728166  0.261085  0.592971  0.703707  0.328769  0.038675   
1635  0.882940  0.476897  0.238997  0.783922  0.633920  0.734025  0.574355   
1636  0.571610  0.556127  0.235254  0.268621  0.487162  0.414232  0.426036   
1637  0.863396  0.472255  0.486584  0.830628  0.243689  0.930204  0.413386   
1638  0.686673  0.922344  0.243908  0.925231  0.087662  0.530651  0.785181   

             7  
0     0.455681  
1     0.303357  
2     0.345328  
3     0.240850  
4     0.523662  
...        ...  
1634  0.170259  
1635  0.492692  
1636  0.635424  
1637  0.257104  
1638  0.653805  

[1639 rows x 8 columns]
<class 'numpy.ndarray'>
working on 
../data/r/189/reg_full_MCAR_0.1_1
4.257601022720337
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-19 17:50:24,228] A new study created in memory with name: no-name-d35b81b4-4047-4c92-baaa-365300eb2e67
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-19 17:50:24,450] Trial 15 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 15 with value: 0.2830913759354646.
[I 2024-09-19 17:50:24,563] Trial 7 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:24,647] Trial 13 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 15 with value: 0.2830913759354646.
running
running
[I 2024-09-19 17:50:27,709] Trial 0 finished with value: 0.28316730805162843 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2511, 'weights': 'uniform'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:28,014] Trial 19 finished with value: 0.5646174484547707 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 15 with value: 0.2830913759354646.
[I 2024-09-19 17:50:28,142] Trial 8 finished with value: 0.2831354369582923 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2744, 'weights': 'distance'}. Best is trial 15 with value: 0.2830913759354646.
running
running
[I 2024-09-19 17:50:29,091] Trial 4 finished with value: 0.28316556466682685 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 5, 'imputation_order': 'random'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:29,357] Trial 22 finished with value: 0.28435747678829315 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:30,832] Trial 20 finished with value: 0.2830945603617376 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5010, 'weights': 'distance'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:31,397] Trial 6 finished with value: 0.4135616398037012 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:33,229] Trial 11 finished with value: 0.3121423276659725 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 3, 'imputation_order': 'descending'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:34,352] Trial 18 finished with value: 0.4150626627182463 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 5, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:34,501] Trial 9 finished with value: 0.31189839379885587 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 4, 'imputation_order': 'ascending'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:44,145] Trial 24 finished with value: 0.3135252727887702 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:48,747] Trial 2 finished with value: 0.4923868240997768 and parameters: {'model_name': 'GAIN', 'batch_size': 7, 'hint_rate': 0.3194304155404586, 'alpha': 12, 'iterations': 2, 'learning_rate': 0.00011429714675793501, 'p_miss': 0.2696274455968388}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:49,081] Trial 1 finished with value: 0.5285840143051557 and parameters: {'model_name': 'GAIN', 'batch_size': 57, 'hint_rate': 0.7409978976982696, 'alpha': 4, 'iterations': 3, 'learning_rate': 0.00240205228838283, 'p_miss': 0.022814178384583234}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:49,393] Trial 12 finished with value: 0.49641378067794334 and parameters: {'model_name': 'GAIN', 'batch_size': 38, 'hint_rate': 0.4058260352371061, 'alpha': 76, 'iterations': 4, 'learning_rate': 0.006913039799777103, 'p_miss': 0.19429168741675165}. Best is trial 15 with value: 0.2830913759354646.
running
[I 2024-09-19 17:50:49,652] Trial 28 finished with value: 0.2817128621237769 and parameters: {'model_name': 'VAE', 'batch_size': 14, 'iterations': 2, 'learning_rate': 0.0006170507231507815, 'p_miss': 0.18849754595433554}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:50:50,196] Trial 5 finished with value: 0.2884132938163229 and parameters: {'model_name': 'VAE', 'batch_size': 13, 'iterations': 3, 'learning_rate': 0.00012872268422800428, 'p_miss': 0.13671724129479312}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:50:53,495] Trial 26 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.3625079202609619, 'alpha': 59, 'iterations': 130, 'learning_rate': 0.0004216986760066205, 'p_miss': 0.15957163752452821}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:50:56,104] Trial 16 finished with value: 0.5081258831375072 and parameters: {'model_name': 'GAIN', 'batch_size': 21, 'hint_rate': 0.45102124156728773, 'alpha': 14, 'iterations': 37, 'learning_rate': 0.0015222909889719433, 'p_miss': 0.1329023474533987}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:51:05,426] Trial 25 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 10, 'hint_rate': 0.5755721736493009, 'alpha': 65, 'iterations': 89, 'learning_rate': 0.010831190477348991, 'p_miss': 0.06606275899667705}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:52:23,092] Trial 29 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.8423611172129717, 'alpha': 86, 'iterations': 2740, 'learning_rate': 0.0008509757311655721, 'p_miss': 0.05805119348030581}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:54:36,384] Trial 14 finished with value: 0.51138282162844 and parameters: {'model_name': 'GAIN', 'batch_size': 685, 'hint_rate': 0.8557151361999741, 'alpha': 66, 'iterations': 1234, 'learning_rate': 0.0001118299359967177, 'p_miss': 0.13815759810742467}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:09,788] Trial 39 finished with value: 0.2885412921641011 and parameters: {'model_name': 'VAE', 'batch_size': 244, 'iterations': 17, 'learning_rate': 0.02200175334587144, 'p_miss': 0.28074280810203545}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:09,953] Trial 40 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:10,579] Trial 41 finished with value: 0.28932586827083784 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 1, 'learning_rate': 0.08668795492661803, 'p_miss': 0.2218222526005605}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:10,734] Trial 42 finished with value: 0.5646174484547707 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,042] Trial 21 finished with value: 0.2891246321950986 and parameters: {'model_name': 'VAE', 'batch_size': 69, 'iterations': 500, 'learning_rate': 0.04850495354526044, 'p_miss': 0.03722892202036099}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,209] Trial 44 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,350] Trial 45 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,502] Trial 46 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,636] Trial 47 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:34,772] Trial 48 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:47,680] Trial 10 finished with value: 0.28460379257747237 and parameters: {'model_name': 'VAE', 'batch_size': 4, 'iterations': 706, 'learning_rate': 0.0001663453982659844, 'p_miss': 0.13803630049346124}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:47,831] Trial 50 finished with value: 0.2830913759354646 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:55:48,973] Trial 51 finished with value: 0.2865900663447872 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 41, 'weights': 'uniform'}. Best is trial 28 with value: 0.2817128621237769.
running
[I 2024-09-19 17:56:05,853] Trial 52 finished with value: 0.2797946500273262 and parameters: {'model_name': 'VAE', 'batch_size': 136, 'iterations': 15, 'learning_rate': 0.00044924788995316444, 'p_miss': 0.23152829671723058}. Best is trial 52 with value: 0.2797946500273262.
running
[I 2024-09-19 17:56:25,153] Trial 53 finished with value: 0.283679966485802 and parameters: {'model_name': 'VAE', 'batch_size': 227, 'iterations': 12, 'learning_rate': 0.0005325353951514548, 'p_miss': 0.2356149100425266}. Best is trial 52 with value: 0.2797946500273262.
running
[I 2024-09-19 17:56:35,328] Trial 54 finished with value: 0.2784690712874269 and parameters: {'model_name': 'VAE', 'batch_size': 162, 'iterations': 9, 'learning_rate': 0.00038681294313148263, 'p_miss': 0.17733088303266764}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:56:49,025] Trial 55 finished with value: 0.28105167712510915 and parameters: {'model_name': 'VAE', 'batch_size': 152, 'iterations': 11, 'learning_rate': 0.00034158682706883806, 'p_miss': 0.190237826705208}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:57:01,203] Trial 56 finished with value: 0.28399155634830514 and parameters: {'model_name': 'VAE', 'batch_size': 182, 'iterations': 10, 'learning_rate': 0.0003266863054427951, 'p_miss': 0.18627654039668642}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:57:27,913] Trial 57 finished with value: 0.2818630962190905 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 28, 'learning_rate': 0.0008253326103404089, 'p_miss': 0.21550065972682583}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:57:54,073] Trial 58 finished with value: 0.28118686714152763 and parameters: {'model_name': 'VAE', 'batch_size': 122, 'iterations': 29, 'learning_rate': 0.0009990207259484094, 'p_miss': 0.21199786379695654}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:58:00,099] Trial 27 finished with value: 0.5174662055919352 and parameters: {'model_name': 'GAIN', 'batch_size': 12, 'hint_rate': 0.3189917724811979, 'alpha': 81, 'iterations': 2614, 'learning_rate': 0.002015310131475248, 'p_miss': 0.13023578069902397}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:58:12,803] Trial 60 finished with value: 0.28625920241086933 and parameters: {'model_name': 'VAE', 'batch_size': 322, 'iterations': 7, 'learning_rate': 0.00028028760820900084, 'p_miss': 0.1867667309876264}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:58:16,856] Trial 59 finished with value: 0.28155412996203233 and parameters: {'model_name': 'VAE', 'batch_size': 549, 'iterations': 8, 'learning_rate': 0.00025360965862895575, 'p_miss': 0.17992096006083297}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 17:58:58,460] Trial 17 finished with value: 0.2890337461392514 and parameters: {'model_name': 'VAE', 'batch_size': 82, 'iterations': 593, 'learning_rate': 0.000505571843086817, 'p_miss': 0.10632166036419868}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:01:03,983] Trial 61 finished with value: 0.284920147969911 and parameters: {'model_name': 'VAE', 'batch_size': 584, 'iterations': 48, 'learning_rate': 0.0008106606893837458, 'p_miss': 0.24856414755520037}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:01:21,901] Trial 64 finished with value: 0.28115846592810756 and parameters: {'model_name': 'VAE', 'batch_size': 131, 'iterations': 17, 'learning_rate': 0.0002521510423679688, 'p_miss': 0.1637701627791149}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:01:41,005] Trial 62 finished with value: 0.27876846230793006 and parameters: {'model_name': 'VAE', 'batch_size': 945, 'iterations': 39, 'learning_rate': 0.00026347506047007767, 'p_miss': 0.24552797943472787}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:01:41,134] Trial 63 finished with value: 0.2800717526817028 and parameters: {'model_name': 'VAE', 'batch_size': 817, 'iterations': 40, 'learning_rate': 0.0002157887893231388, 'p_miss': 0.24638644901462886}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:01:41,486] Trial 65 finished with value: 0.2828144246546892 and parameters: {'model_name': 'VAE', 'batch_size': 132, 'iterations': 23, 'learning_rate': 0.0002147970825226912, 'p_miss': 0.20935014443430777}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:02:03,367] Trial 66 finished with value: 0.2807911107638027 and parameters: {'model_name': 'VAE', 'batch_size': 141, 'iterations': 21, 'learning_rate': 0.0002078260391080018, 'p_miss': 0.21272818318127695}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:02:28,218] Trial 33 finished with value: 0.349361347838529 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 2067, 'learning_rate': 0.0003743758097827102, 'p_miss': 0.1220054173263356}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:02:29,878] Trial 43 finished with value: 0.2884754786761063 and parameters: {'model_name': 'VAE', 'batch_size': 100, 'iterations': 503, 'learning_rate': 0.00044781934730788657, 'p_miss': 0.22999769593843566}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:08:28,361] Trial 69 finished with value: 0.28201352578945266 and parameters: {'model_name': 'VAE', 'batch_size': 836, 'iterations': 86, 'learning_rate': 0.0003677745002343941, 'p_miss': 0.2539589202137876}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:12:12,856] Trial 67 finished with value: 0.28081342026112815 and parameters: {'model_name': 'VAE', 'batch_size': 993, 'iterations': 127, 'learning_rate': 0.0001800944435350387, 'p_miss': 0.25660058842427613}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:12:14,097] Trial 73 finished with value: 0.2830913759354646 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6157, 'weights': 'uniform'}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:12:17,318] Trial 68 finished with value: 0.28246640353383207 and parameters: {'model_name': 'VAE', 'batch_size': 924, 'iterations': 146, 'learning_rate': 0.00026148582683364153, 'p_miss': 0.248315537625119}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:13:33,522] Trial 71 finished with value: 0.28147577764132903 and parameters: {'model_name': 'VAE', 'batch_size': 908, 'iterations': 145, 'learning_rate': 0.00019363428817747002, 'p_miss': 0.2592602957796191}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:14:19,729] Trial 74 finished with value: 0.27974445518186464 and parameters: {'model_name': 'VAE', 'batch_size': 389, 'iterations': 62, 'learning_rate': 0.00017747771213418468, 'p_miss': 0.25781168022136164}. Best is trial 54 with value: 0.2784690712874269.
running
[I 2024-09-19 18:15:22,965] Trial 76 finished with value: 0.2776664396811679 and parameters: {'model_name': 'VAE', 'batch_size': 390, 'iterations': 55, 'learning_rate': 0.0001323501399053645, 'p_miss': 0.29178760967879347}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:16:13,328] Trial 23 finished with value: 0.2920500701131959 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 6, 'imputation_order': 'descending'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:16:17,725] Trial 77 finished with value: 0.2854862542162945 and parameters: {'model_name': 'VAE', 'batch_size': 359, 'iterations': 54, 'learning_rate': 0.00013729079158624502, 'p_miss': 0.28851426334662195}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:16:30,326] Trial 80 finished with value: 0.28040988502520925 and parameters: {'model_name': 'VAE', 'batch_size': 473, 'iterations': 5, 'learning_rate': 0.00010022405989996014, 'p_miss': 0.27400617954497614}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:16:42,519] Trial 81 finished with value: 0.28010231254720275 and parameters: {'model_name': 'VAE', 'batch_size': 419, 'iterations': 5, 'learning_rate': 0.0001026803373949101, 'p_miss': 0.29912229381625954}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:17:28,738] Trial 78 finished with value: 0.2831705279367899 and parameters: {'model_name': 'VAE', 'batch_size': 432, 'iterations': 56, 'learning_rate': 0.00010118073809875925, 'p_miss': 0.29328049908335097}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:17:30,176] Trial 83 finished with value: 0.2830876770469329 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:03,936] Trial 72 finished with value: 0.2848035690768213 and parameters: {'model_name': 'VAE', 'batch_size': 376, 'iterations': 222, 'learning_rate': 0.00017482994476725885, 'p_miss': 0.29239090176713156}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:05,116] Trial 85 finished with value: 0.2854330837434018 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 60, 'weights': 'distance'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:07,389] Trial 75 finished with value: 0.2828162967252549 and parameters: {'model_name': 'VAE', 'batch_size': 408, 'iterations': 164, 'learning_rate': 0.0001817502739734852, 'p_miss': 0.29030815295257073}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:08,585] Trial 86 finished with value: 0.280443937287871 and parameters: {'model_name': 'VAE', 'batch_size': 43, 'iterations': 6, 'learning_rate': 0.00011499643391748398, 'p_miss': 0.2737901795428225}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:14,716] Trial 87 finished with value: 0.2836396500523281 and parameters: {'model_name': 'VAE', 'batch_size': 260, 'iterations': 4, 'learning_rate': 0.0001016120367411444, 'p_miss': 0.26980302097853115}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:18,630] Trial 88 finished with value: 0.28413609858327704 and parameters: {'model_name': 'VAE', 'batch_size': 550, 'iterations': 4, 'learning_rate': 0.00012850410905726763, 'p_miss': 0.26789395709394087}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:20,840] Trial 79 finished with value: 0.28024375121408945 and parameters: {'model_name': 'VAE', 'batch_size': 393, 'iterations': 55, 'learning_rate': 0.00012414211691750613, 'p_miss': 0.298120425595585}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:28,136] Trial 89 finished with value: 0.28419849537666675 and parameters: {'model_name': 'VAE', 'batch_size': 596, 'iterations': 4, 'learning_rate': 0.0001465817621995675, 'p_miss': 0.23848546356917652}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:18:28,333] Trial 90 finished with value: 0.28135154349968294 and parameters: {'model_name': 'VAE', 'batch_size': 663, 'iterations': 2, 'learning_rate': 0.00014829684427419566, 'p_miss': 0.23380524223840818}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:19:23,700] Trial 92 finished with value: 0.28231470330690694 and parameters: {'model_name': 'VAE', 'batch_size': 283, 'iterations': 40, 'learning_rate': 0.00016498210535386093, 'p_miss': 0.28078786507137}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:20:40,652] Trial 70 finished with value: 0.2843219026010137 and parameters: {'model_name': 'VAE', 'batch_size': 980, 'iterations': 221, 'learning_rate': 0.00018709066444127546, 'p_miss': 0.25785222188713836}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:24:34,223] Trial 82 finished with value: 0.2816696760056205 and parameters: {'model_name': 'VAE', 'batch_size': 394, 'iterations': 247, 'learning_rate': 0.00013779470521975236, 'p_miss': 0.29476019033712236}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:26:00,549] Trial 96 finished with value: 0.2839818615021588 and parameters: {'model_name': 'VAE', 'batch_size': 207, 'iterations': 78, 'learning_rate': 0.00010045004027000607, 'p_miss': 0.27918370104913004}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:26:51,007] Trial 84 finished with value: 0.28466849120539506 and parameters: {'model_name': 'VAE', 'batch_size': 307, 'iterations': 315, 'learning_rate': 0.00014566762209391443, 'p_miss': 0.27395290335015865}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:30:51,457] Trial 3 finished with value: 0.29857997757947397 and parameters: {'model_name': 'VAE', 'batch_size': 5, 'iterations': 8813, 'learning_rate': 0.0004675939319020486, 'p_miss': 0.09912903967576181}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:48:02,803] Trial 93 finished with value: 0.2914573061065841 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:49:03,458] Trial 94 finished with value: 0.2904385225381251 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:49:07,980] Trial 101 finished with value: 0.4814561664628939 and parameters: {'model_name': 'GAIN', 'batch_size': 470, 'hint_rate': 0.03702050113959371, 'alpha': 33, 'iterations': 33, 'learning_rate': 0.0002515443600943586, 'p_miss': 0.29688422955214155}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:49:45,301] Trial 100 finished with value: 0.2887679054874435 and parameters: {'model_name': 'VAE', 'batch_size': 530, 'iterations': 36, 'learning_rate': 0.00721391479355175, 'p_miss': 0.2989983511484862}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:19,178] Trial 95 finished with value: 0.29130220258167167 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:22,497] Trial 102 finished with value: 0.2881698642952849 and parameters: {'model_name': 'VAE', 'batch_size': 726, 'iterations': 15, 'learning_rate': 0.005445846029539208, 'p_miss': 0.299966282570603}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:29,374] Trial 103 finished with value: 0.2808797027776973 and parameters: {'model_name': 'VAE', 'batch_size': 766, 'iterations': 14, 'learning_rate': 0.0005414089800527301, 'p_miss': 0.24256962155524794}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:34,394] Trial 106 finished with value: 0.2808067755017779 and parameters: {'model_name': 'VAE', 'batch_size': 62, 'iterations': 6, 'learning_rate': 0.00012199389570831887, 'p_miss': 0.26379780032098527}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:40,082] Trial 107 finished with value: 0.27980840030458165 and parameters: {'model_name': 'VAE', 'batch_size': 189, 'iterations': 6, 'learning_rate': 0.0001227857663789354, 'p_miss': 0.28003185579888273}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:44,038] Trial 108 finished with value: 0.27836709171918816 and parameters: {'model_name': 'VAE', 'batch_size': 183, 'iterations': 3, 'learning_rate': 0.0002971928447486931, 'p_miss': 0.28213698526111025}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:52,378] Trial 109 finished with value: 0.27816522296163704 and parameters: {'model_name': 'VAE', 'batch_size': 207, 'iterations': 9, 'learning_rate': 0.0003272438195472987, 'p_miss': 0.2822850869121078}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:53,271] Trial 110 finished with value: 0.28791549315282006 and parameters: {'model_name': 'VAE', 'batch_size': 160, 'iterations': 1, 'learning_rate': 0.0003293048429807156, 'p_miss': 0.2821462086062113}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:54,729] Trial 111 finished with value: 0.2830731755370043 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4169, 'weights': 'uniform'}. Best is trial 76 with value: 0.2776664396811679.
running
[I 2024-09-19 18:50:57,981] Trial 112 finished with value: 0.2768769674778699 and parameters: {'model_name': 'VAE', 'batch_size': 200, 'iterations': 2, 'learning_rate': 0.0002953056740759565, 'p_miss': 0.22329408593245606}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:50:58,753] Trial 37 finished with value: 0.28849878347452645 and parameters: {'model_name': 'VAE', 'batch_size': 634, 'iterations': 1557, 'learning_rate': 0.0446963057720783, 'p_miss': 0.2911026929537084}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:00,215] Trial 113 finished with value: 0.28246441099882647 and parameters: {'model_name': 'VAE', 'batch_size': 90, 'iterations': 2, 'learning_rate': 0.0004355281104090828, 'p_miss': 0.22439551027443103}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:00,450] Trial 114 finished with value: 0.29098501630722795 and parameters: {'model_name': 'VAE', 'batch_size': 86, 'iterations': 2, 'learning_rate': 0.0004059458312612394, 'p_miss': 0.22318664536409166}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:03,780] Trial 116 finished with value: 0.2799117875893376 and parameters: {'model_name': 'VAE', 'batch_size': 193, 'iterations': 3, 'learning_rate': 0.0003000733513164604, 'p_miss': 0.20099470595200114}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:07,621] Trial 104 finished with value: 0.27983797531092686 and parameters: {'model_name': 'VAE', 'batch_size': 716, 'iterations': 17, 'learning_rate': 0.0002950463609796032, 'p_miss': 0.2664776323695689}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:11,284] Trial 117 finished with value: 0.2863090028313159 and parameters: {'model_name': 'VAE', 'batch_size': 183, 'iterations': 8, 'learning_rate': 0.0003016843403739142, 'p_miss': 0.19988202355910534}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:13,994] Trial 115 finished with value: 0.28318815755569365 and parameters: {'model_name': 'VAE', 'batch_size': 201, 'iterations': 10, 'learning_rate': 0.0006446571143092067, 'p_miss': 0.24441270169648735}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:14,767] Trial 120 finished with value: 0.49837688615066045 and parameters: {'model_name': 'GAIN', 'batch_size': 265, 'hint_rate': 0.11801623714675091, 'alpha': 97, 'iterations': 3, 'learning_rate': 0.0013492780512784216, 'p_miss': 0.19616765616891935}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:16,232] Trial 119 finished with value: 0.28210586451582764 and parameters: {'model_name': 'VAE', 'batch_size': 213, 'iterations': 3, 'learning_rate': 0.001312893804740783, 'p_miss': 0.20149560992214155}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:20,393] Trial 118 finished with value: 0.27964332241182044 and parameters: {'model_name': 'VAE', 'batch_size': 209, 'iterations': 9, 'learning_rate': 0.0006942820843256997, 'p_miss': 0.19710239556138848}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:29,989] Trial 105 finished with value: 0.28168634902104106 and parameters: {'model_name': 'VAE', 'batch_size': 197, 'iterations': 64, 'learning_rate': 0.0003170191103165993, 'p_miss': 0.2667079839245834}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:30,339] Trial 122 finished with value: 0.2812493821264156 and parameters: {'model_name': 'VAE', 'batch_size': 118, 'iterations': 20, 'learning_rate': 0.00029425496203325626, 'p_miss': 0.1788887336943119}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:33,323] Trial 121 finished with value: 0.28054795471725125 and parameters: {'model_name': 'VAE', 'batch_size': 111, 'iterations': 20, 'learning_rate': 0.00022777497530259485, 'p_miss': 0.1769966764864086}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:34,437] Trial 123 finished with value: 0.2806625816993768 and parameters: {'model_name': 'VAE', 'batch_size': 117, 'iterations': 20, 'learning_rate': 0.00057096775444218, 'p_miss': 0.1806286118657771}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:38,362] Trial 125 finished with value: 0.28320047950729527 and parameters: {'model_name': 'VAE', 'batch_size': 146, 'iterations': 9, 'learning_rate': 0.0005671399599317562, 'p_miss': 0.16595526310692502}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:43,591] Trial 126 finished with value: 0.2825634159593651 and parameters: {'model_name': 'VAE', 'batch_size': 175, 'iterations': 9, 'learning_rate': 0.0006011198942459083, 'p_miss': 0.15370045586704967}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:45,661] Trial 127 finished with value: 0.28202338021169343 and parameters: {'model_name': 'VAE', 'batch_size': 159, 'iterations': 12, 'learning_rate': 0.0004632489974089288, 'p_miss': 0.20503533017843562}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:46,256] Trial 124 finished with value: 0.28497935953331516 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 23, 'learning_rate': 0.00062960332305707, 'p_miss': 0.1733479665281714}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:49,838] Trial 130 finished with value: 0.2823974548246567 and parameters: {'model_name': 'VAE', 'batch_size': 246, 'iterations': 3, 'learning_rate': 0.00022632592312257704, 'p_miss': 0.21748282649310102}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:51,506] Trial 131 finished with value: 0.283353576982553 and parameters: {'model_name': 'VAE', 'batch_size': 322, 'iterations': 3, 'learning_rate': 0.0003720904156271578, 'p_miss': 0.22889190196502138}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:52,952] Trial 133 finished with value: 0.28314121871274794 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1625, 'weights': 'distance'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:55,162] Trial 134 finished with value: 0.2819607499380486 and parameters: {'model_name': 'VAE', 'batch_size': 23, 'iterations': 7, 'learning_rate': 0.00027010952541635705, 'p_miss': 0.2612890172351199}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:51:55,319] Trial 128 finished with value: 0.2870056535834441 and parameters: {'model_name': 'VAE', 'batch_size': 168, 'iterations': 12, 'learning_rate': 0.0003867249529513708, 'p_miss': 0.2828972902102242}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:52:03,461] Trial 129 finished with value: 0.2805107125701633 and parameters: {'model_name': 'VAE', 'batch_size': 314, 'iterations': 14, 'learning_rate': 0.0004670661284183446, 'p_miss': 0.28439833231212636}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:52:07,825] Trial 136 finished with value: 0.28157941700041855 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 40, 'learning_rate': 0.00021255189011716856, 'p_miss': 0.2528031455165744}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:52:26,067] Trial 135 finished with value: 0.2805401132397201 and parameters: {'model_name': 'VAE', 'batch_size': 2, 'iterations': 101, 'learning_rate': 0.0003952581530460948, 'p_miss': 0.2864637941910215}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:52:41,775] Trial 137 finished with value: 0.28102915934839706 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 105, 'learning_rate': 0.00020720982764116844, 'p_miss': 0.25009327413268084}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:52:54,123] Trial 139 finished with value: 0.28406432285251165 and parameters: {'model_name': 'VAE', 'batch_size': 238, 'iterations': 27, 'learning_rate': 0.00017196638720717928, 'p_miss': 0.24823739341245968}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:14,796] Trial 141 finished with value: 0.280827699303988 and parameters: {'model_name': 'VAE', 'batch_size': 736, 'iterations': 5, 'learning_rate': 0.0002592670934429965, 'p_miss': 0.1912597184034422}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:17,504] Trial 142 finished with value: 0.27793374622598294 and parameters: {'model_name': 'VAE', 'batch_size': 482, 'iterations': 1, 'learning_rate': 0.0003242008071108639, 'p_miss': 0.23224859964558991}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:18,039] Trial 143 finished with value: 0.4951675515858325 and parameters: {'model_name': 'GAIN', 'batch_size': 482, 'hint_rate': 0.9793656636760857, 'alpha': 37, 'iterations': 1, 'learning_rate': 0.003160430002736874, 'p_miss': 0.23667075247221986}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:19,597] Trial 140 finished with value: 0.2796922116802786 and parameters: {'model_name': 'VAE', 'batch_size': 233, 'iterations': 29, 'learning_rate': 0.0001644463424965502, 'p_miss': 0.23576390102149428}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:27,862] Trial 144 finished with value: 0.2835297284480419 and parameters: {'model_name': 'VAE', 'batch_size': 332, 'iterations': 6, 'learning_rate': 0.0002995891834334023, 'p_miss': 0.20619806444004932}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:53:57,811] Trial 146 finished with value: 0.2807951324506891 and parameters: {'model_name': 'VAE', 'batch_size': 227, 'iterations': 27, 'learning_rate': 0.00033736011829126815, 'p_miss': 0.22982898910987173}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:54:33,138] Trial 138 finished with value: 0.2881449073732996 and parameters: {'model_name': 'VAE', 'batch_size': 231, 'iterations': 107, 'learning_rate': 0.0024961138462980662, 'p_miss': 0.24902823981388544}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:55:24,987] Trial 148 finished with value: 0.2841780513126102 and parameters: {'model_name': 'VAE', 'batch_size': 261, 'iterations': 48, 'learning_rate': 0.0002432080228461935, 'p_miss': 0.21758046492636035}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:55:35,561] Trial 97 finished with value: 0.2905759808262799 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:55:39,621] Trial 150 finished with value: 0.28435578835242736 and parameters: {'model_name': 'VAE', 'batch_size': 143, 'iterations': 4, 'learning_rate': 0.000165976284999687, 'p_miss': 0.2760849472324566}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:55:53,361] Trial 149 finished with value: 0.2860435555714277 and parameters: {'model_name': 'VAE', 'batch_size': 358, 'iterations': 16, 'learning_rate': 0.000171192898431544, 'p_miss': 0.24019897881819427}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:56:04,876] Trial 151 finished with value: 0.2781389496187777 and parameters: {'model_name': 'VAE', 'batch_size': 286, 'iterations': 17, 'learning_rate': 0.00034563152762135947, 'p_miss': 0.01847573218446419}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:56:17,349] Trial 152 finished with value: 0.27753003019341105 and parameters: {'model_name': 'VAE', 'batch_size': 616, 'iterations': 7, 'learning_rate': 0.0003463212818079652, 'p_miss': 0.27000558075522785}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:56:22,036] Trial 154 finished with value: 0.28129523115842686 and parameters: {'model_name': 'VAE', 'batch_size': 72, 'iterations': 7, 'learning_rate': 0.0003493533518376486, 'p_miss': 0.2608339959443387}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:56:28,733] Trial 98 finished with value: 0.291189153366591 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:58:20,790] Trial 155 finished with value: 0.28387505449300066 and parameters: {'model_name': 'VAE', 'batch_size': 303, 'iterations': 68, 'learning_rate': 0.0006986047518846927, 'p_miss': 0.10161334713154678}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:58:58,968] Trial 157 finished with value: 0.2795208629084116 and parameters: {'model_name': 'VAE', 'batch_size': 625, 'iterations': 11, 'learning_rate': 0.0005048118558616146, 'p_miss': 0.011782456858585089}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 18:59:48,928] Trial 38 finished with value: 0.28821298031023085 and parameters: {'model_name': 'VAE', 'batch_size': 244, 'iterations': 3665, 'learning_rate': 0.08085511825398073, 'p_miss': 0.2730190619573122}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:00:16,893] Trial 159 finished with value: 0.28050682547464467 and parameters: {'model_name': 'VAE', 'batch_size': 593, 'iterations': 11, 'learning_rate': 0.00042613835258587554, 'p_miss': 0.01326109071303044}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:00:19,525] Trial 99 finished with value: 0.2909573563637866 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:00:40,738] Trial 161 finished with value: 0.28602528533756555 and parameters: {'model_name': 'VAE', 'batch_size': 528, 'iterations': 8, 'learning_rate': 0.0005098860410622335, 'p_miss': 0.037840176189638856}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:00:40,878] Trial 162 finished with value: 0.28435747678829315 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:01:13,394] Trial 163 finished with value: 0.28156071307764763 and parameters: {'model_name': 'VAE', 'batch_size': 443, 'iterations': 13, 'learning_rate': 0.0004670170474772708, 'p_miss': 0.017715375770527845}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:01:22,757] Trial 164 finished with value: 0.2798459142666737 and parameters: {'model_name': 'VAE', 'batch_size': 284, 'iterations': 5, 'learning_rate': 0.0007462727306314624, 'p_miss': 0.010303852781292483}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:01:23,944] Trial 165 finished with value: 0.2830913759354646 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5473, 'weights': 'uniform'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:02:25,601] Trial 166 finished with value: 0.28476036499570007 and parameters: {'model_name': 'VAE', 'batch_size': 655, 'iterations': 17, 'learning_rate': 0.00026534925489608277, 'p_miss': 0.027033670524787834}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:03:09,040] Trial 167 finished with value: 0.2808768650947987 and parameters: {'model_name': 'VAE', 'batch_size': 817, 'iterations': 9, 'learning_rate': 0.0009572836388097941, 'p_miss': 0.268706032649962}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:40:15,026] Trial 49 finished with value: 0.2884492861119245 and parameters: {'model_name': 'VAE', 'batch_size': 159, 'iterations': 7813, 'learning_rate': 0.0003458506202980474, 'p_miss': 0.22367113874541067}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:41:24,305] Trial 169 finished with value: 0.28145857701306526 and parameters: {'model_name': 'VAE', 'batch_size': 470, 'iterations': 26, 'learning_rate': 0.0001942436364057389, 'p_miss': 0.25543064509521657}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:42:49,171] Trial 170 finished with value: 0.2844262144622114 and parameters: {'model_name': 'VAE', 'batch_size': 390, 'iterations': 33, 'learning_rate': 0.00031402127564549606, 'p_miss': 0.03468404299892147}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:44:08,833] Trial 171 finished with value: 0.2862405316846452 and parameters: {'model_name': 'VAE', 'batch_size': 642, 'iterations': 18, 'learning_rate': 0.00015129437761008307, 'p_miss': 0.06200944299098181}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:44:24,330] Trial 172 finished with value: 0.2781846005969036 and parameters: {'model_name': 'VAE', 'batch_size': 183, 'iterations': 11, 'learning_rate': 0.00038283025576632177, 'p_miss': 0.14681684926228547}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:44:36,141] Trial 173 finished with value: 0.2824152712307631 and parameters: {'model_name': 'VAE', 'batch_size': 187, 'iterations': 11, 'learning_rate': 0.00038869894945750837, 'p_miss': 0.08470801434936864}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:44:42,940] Trial 174 finished with value: 0.28474948329339467 and parameters: {'model_name': 'VAE', 'batch_size': 141, 'iterations': 7, 'learning_rate': 0.00012409189632206423, 'p_miss': 0.12266584323165382}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:45:41,435] Trial 175 finished with value: 0.28014788919528166 and parameters: {'model_name': 'VAE', 'batch_size': 204, 'iterations': 44, 'learning_rate': 0.000507493423132298, 'p_miss': 0.29174316540029827}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:46:57,579] Trial 176 finished with value: 0.27931504980057814 and parameters: {'model_name': 'VAE', 'batch_size': 911, 'iterations': 14, 'learning_rate': 0.0003346413880989475, 'p_miss': 0.14882527144218333}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:46:57,909] Trial 132 finished with value: 0.29018627770599714 and parameters: {'model_name': 'VAE', 'batch_size': 28, 'iterations': 9314, 'learning_rate': 0.0003709855102718103, 'p_miss': 0.2305596665147406}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:47:18,827] Trial 178 finished with value: 0.28072633476674314 and parameters: {'model_name': 'VAE', 'batch_size': 358, 'iterations': 10, 'learning_rate': 0.00043056256827574336, 'p_miss': 0.16999542973705117}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:47:20,732] Trial 177 finished with value: 0.2803477488811232 and parameters: {'model_name': 'VAE', 'batch_size': 276, 'iterations': 14, 'learning_rate': 0.0004111560345270177, 'p_miss': 0.1323793899283289}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:47:49,776] Trial 180 finished with value: 0.28641125000609674 and parameters: {'model_name': 'VAE', 'batch_size': 817, 'iterations': 6, 'learning_rate': 0.0002332073059074629, 'p_miss': 0.139117484083905}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:47:54,499] Trial 181 finished with value: 0.29149957882995825 and parameters: {'model_name': 'VAE', 'batch_size': 166, 'iterations': 2, 'learning_rate': 0.02586015683678125, 'p_miss': 0.16065965089984066}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:47:58,343] Trial 182 finished with value: 0.5067168830741476 and parameters: {'model_name': 'GAIN', 'batch_size': 920, 'hint_rate': 0.6981572752376171, 'alpha': 40, 'iterations': 24, 'learning_rate': 0.0003566870690217036, 'p_miss': 0.14321303686665038}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:48:23,478] Trial 183 finished with value: 0.2840361944649451 and parameters: {'model_name': 'VAE', 'batch_size': 545, 'iterations': 9, 'learning_rate': 0.00028547649023893826, 'p_miss': 0.15036506917227466}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:48:43,026] Trial 179 finished with value: 0.28159002218132334 and parameters: {'model_name': 'VAE', 'batch_size': 902, 'iterations': 15, 'learning_rate': 0.00023001806193338541, 'p_miss': 0.14763684572505142}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:49:12,836] Trial 184 finished with value: 0.28118557168615393 and parameters: {'model_name': 'VAE', 'batch_size': 218, 'iterations': 34, 'learning_rate': 0.0003351796141062102, 'p_miss': 0.07212268088923832}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:49:24,660] Trial 185 finished with value: 0.2768864622933949 and parameters: {'model_name': 'VAE', 'batch_size': 221, 'iterations': 32, 'learning_rate': 0.00033049854830062455, 'p_miss': 0.2776616645015147}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:49:55,560] Trial 186 finished with value: 0.28166484781526585 and parameters: {'model_name': 'VAE', 'batch_size': 729, 'iterations': 13, 'learning_rate': 0.0002825025660234386, 'p_miss': 0.2788495515058542}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:50:12,827] Trial 188 finished with value: 0.28404320421721974 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 51, 'learning_rate': 0.00034360519808514586, 'p_miss': 0.28748924459020975}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:50:24,508] Trial 187 finished with value: 0.2793308891190202 and parameters: {'model_name': 'VAE', 'batch_size': 182, 'iterations': 67, 'learning_rate': 0.00026558114153435187, 'p_miss': 0.2792953547541538}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:51:11,269] Trial 189 finished with value: 0.28275227447722795 and parameters: {'model_name': 'VAE', 'batch_size': 128, 'iterations': 66, 'learning_rate': 0.0005129787488251778, 'p_miss': 0.2754130455292606}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:51:44,460] Trial 190 finished with value: 0.2838169653428003 and parameters: {'model_name': 'VAE', 'batch_size': 125, 'iterations': 89, 'learning_rate': 0.0004776986771970537, 'p_miss': 0.27265741491834894}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:53:15,640] Trial 191 finished with value: 0.28136179148563106 and parameters: {'model_name': 'VAE', 'batch_size': 257, 'iterations': 74, 'learning_rate': 0.0002569387185354602, 'p_miss': 0.24168520038541483}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:53:17,775] Trial 192 finished with value: 0.27869158816943673 and parameters: {'model_name': 'VAE', 'batch_size': 247, 'iterations': 60, 'learning_rate': 0.0001939329098437503, 'p_miss': 0.23516147372558224}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:53:52,953] Trial 193 finished with value: 0.28452394086190214 and parameters: {'model_name': 'VAE', 'batch_size': 224, 'iterations': 34, 'learning_rate': 0.00020802461692480097, 'p_miss': 0.26386846946988535}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:54:43,679] Trial 194 finished with value: 0.2821954230952485 and parameters: {'model_name': 'VAE', 'batch_size': 300, 'iterations': 54, 'learning_rate': 0.00020667581122656305, 'p_miss': 0.23455007139513448}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:55:26,096] Trial 195 finished with value: 0.2801423588637001 and parameters: {'model_name': 'VAE', 'batch_size': 317, 'iterations': 55, 'learning_rate': 0.0001886742520226896, 'p_miss': 0.05065854509980476}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:55:42,912] Trial 196 finished with value: 0.28313014881983606 and parameters: {'model_name': 'VAE', 'batch_size': 167, 'iterations': 60, 'learning_rate': 0.0003065459160758573, 'p_miss': 0.22963594903202308}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:55:43,123] Trial 198 finished with value: 0.5646174484547707 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 112 with value: 0.2768769674778699.
running
[I 2024-09-19 19:56:05,321] Trial 199 finished with value: 0.2825760350190408 and parameters: {'model_name': 'VAE', 'batch_size': 191, 'iterations': 23, 'learning_rate': 0.0003775096174279756, 'p_miss': 0.22126627494784534}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 19:56:13,616] Trial 197 finished with value: 0.2800762328501755 and parameters: {'model_name': 'VAE', 'batch_size': 192, 'iterations': 43, 'learning_rate': 0.00030564121452670033, 'p_miss': 0.22567237683515196}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 20:03:54,254] Trial 34 finished with value: 0.28911760621895083 and parameters: {'model_name': 'VAE', 'batch_size': 990, 'iterations': 2138, 'learning_rate': 0.07789219762041905, 'p_miss': 0.1473592779571444}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:26:06,209] Trial 35 finished with value: 0.28851045759701105 and parameters: {'model_name': 'VAE', 'batch_size': 880, 'iterations': 4055, 'learning_rate': 0.06523371337865806, 'p_miss': 0.2943532874677639}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:35:15,232] Trial 145 finished with value: 0.2885802786937183 and parameters: {'model_name': 'VAE', 'batch_size': 363, 'iterations': 7159, 'learning_rate': 0.0007752530271819914, 'p_miss': 0.2287032684247437}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:37:41,526] Trial 156 finished with value: 0.28867379008414745 and parameters: {'model_name': 'VAE', 'batch_size': 539, 'iterations': 4371, 'learning_rate': 0.00048650359309834013, 'p_miss': 0.09036787247305746}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:44:59,487] Trial 168 finished with value: 0.2885499734134068 and parameters: {'model_name': 'VAE', 'batch_size': 508, 'iterations': 5374, 'learning_rate': 0.00034676931077133594, 'p_miss': 0.02886640028806095}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:45:34,629] Trial 147 finished with value: 0.28763130314669116 and parameters: {'model_name': 'VAE', 'batch_size': 282, 'iterations': 8954, 'learning_rate': 0.0002538558720994258, 'p_miss': 0.21936204432307352}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 21:46:38,151] Trial 160 finished with value: 0.2886666051131071 and parameters: {'model_name': 'VAE', 'batch_size': 470, 'iterations': 5970, 'learning_rate': 0.0004887953775502378, 'p_miss': 0.08848633329355916}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:02:16,839] Trial 153 finished with value: 0.2889472543121646 and parameters: {'model_name': 'VAE', 'batch_size': 645, 'iterations': 5296, 'learning_rate': 0.0007348271697940039, 'p_miss': 0.08387304782859745}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:25:30,684] Trial 91 finished with value: 0.2887813151283973 and parameters: {'model_name': 'VAE', 'batch_size': 662, 'iterations': 7799, 'learning_rate': 0.004777084675450236, 'p_miss': 0.2989471406528275}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:35:19,676] Trial 36 finished with value: 0.2890500789747178 and parameters: {'model_name': 'VAE', 'batch_size': 674, 'iterations': 8671, 'learning_rate': 0.07839643535216326, 'p_miss': 0.2979606287271036}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:43:39,835] Trial 31 finished with value: 0.28881064618760616 and parameters: {'model_name': 'VAE', 'batch_size': 720, 'iterations': 9144, 'learning_rate': 0.036405471417019615, 'p_miss': 0.10785293056462725}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:45:25,728] Trial 30 finished with value: 0.28872509627329923 and parameters: {'model_name': 'VAE', 'batch_size': 846, 'iterations': 8192, 'learning_rate': 0.044371202151607544, 'p_miss': 0.019255826711888024}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:46:07,120] Trial 158 finished with value: 0.28865585540967953 and parameters: {'model_name': 'VAE', 'batch_size': 602, 'iterations': 9278, 'learning_rate': 0.00048631498106294134, 'p_miss': 0.016779234771264445}. Best is trial 112 with value: 0.2768769674778699.
[I 2024-09-19 22:46:45,962] Trial 32 finished with value: 0.28878980904230184 and parameters: {'model_name': 'VAE', 'batch_size': 921, 'iterations': 7968, 'learning_rate': 0.07801402893552918, 'p_miss': 0.028140370494292882}. Best is trial 112 with value: 0.2768769674778699.
fit
auto fit
auto transform
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64
0.2768769674778699
{'model_name': 'VAE', 'batch_size': 200, 'iterations': 2, 'learning_rate': 0.0002953056740759565, 'p_miss': 0.22329408593245606}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]Generation:  1
Best root_mean_squared_error score: -0.26390259960102935
Generation:   4%|▍         | 1/25 [00:24<09:54, 24.78s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741a0af0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474192770> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474121270> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474125510> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  2
Best root_mean_squared_error score: -0.26352807143763146
Generation:   8%|▊         | 2/25 [00:43<08:03, 21.02s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474167520> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  3
Best root_mean_squared_error score: -0.26352807143763146
Generation:  12%|█▏        | 3/25 [00:48<05:08, 14.01s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474124880> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  4
Best root_mean_squared_error score: -0.26352807143763146
Generation:  16%|█▌        | 4/25 [01:02<04:54, 14.04s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546f9b3d00> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  5
Best root_mean_squared_error score: -0.26352807143763146
Generation:  20%|██        | 5/25 [01:08<03:41, 11.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546d8c2e60> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  6
Best root_mean_squared_error score: -0.26352807143763146
Generation:  24%|██▍       | 6/25 [01:21<03:44, 11.79s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741a74f0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474125630> 

Generation:  7
Best root_mean_squared_error score: -0.26352807143763146
Generation:  28%|██▊       | 7/25 [11:26<1:01:37, 205.43s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741c0dc0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -0.26352807143763146
Generation:  32%|███▏      | 8/25 [11:37<40:40, 143.54s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546f9cc670> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  9
Best root_mean_squared_error score: -0.26352807143763146
Generation:  36%|███▌      | 9/25 [12:01<28:21, 106.35s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546d71a4a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741d75b0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  10
Best root_mean_squared_error score: -0.2635270170034639
Generation:  40%|████      | 10/25 [12:13<19:19, 77.28s/it]Generation:  11
Best root_mean_squared_error score: -0.2635270170034639
Generation:  44%|████▍     | 11/25 [12:40<14:23, 61.68s/it]Generation:  12
Best root_mean_squared_error score: -0.2635270170034639
Generation:  48%|████▊     | 12/25 [13:14<11:33, 53.32s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546d65ffa0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -0.2635270170034639
Generation:  52%|█████▏    | 13/25 [13:31<08:29, 42.46s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546d0745b0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  14
Best root_mean_squared_error score: -0.2635270170034639
Generation:  56%|█████▌    | 14/25 [14:17<07:58, 43.48s/it]Generation:  15
Best root_mean_squared_error score: -0.2635270170034639
Generation:  60%|██████    | 15/25 [14:31<05:44, 34.44s/it]Generation:  16
Best root_mean_squared_error score: -0.2635270170034639
Generation:  64%|██████▍   | 16/25 [14:42<04:08, 27.61s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546c335930> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  17
Best root_mean_squared_error score: -0.2635270170034639
Generation:  68%|██████▊   | 17/25 [14:55<03:03, 22.97s/it]Generation:  18
Best root_mean_squared_error score: -0.2635270170034639
Generation:  72%|███████▏  | 18/25 [15:10<02:24, 20.67s/it]Generation:  19
Best root_mean_squared_error score: -0.2635270170034639
Generation:  76%|███████▌  | 19/25 [15:36<02:13, 22.30s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546ce73a00> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  20
Best root_mean_squared_error score: -0.2635270170034639
Generation:  80%|████████  | 20/25 [18:42<05:57, 71.45s/it]Generation:  21
Best root_mean_squared_error score: -0.2635270170034639
Generation:  84%|████████▍ | 21/25 [18:57<03:38, 54.64s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546f2d3e80> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546d62a1d0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  22
Best root_mean_squared_error score: -0.2635270170034639
Generation:  88%|████████▊ | 22/25 [19:20<02:14, 45.00s/it]Generation:  23
Best root_mean_squared_error score: -0.2635270170034639
Generation:  92%|█████████▏| 23/25 [19:33<01:10, 35.33s/it]Generation:  24
Best root_mean_squared_error score: -0.2635270170034639
Generation:  96%|█████████▌| 24/25 [19:43<00:27, 27.71s/it]Generation:  25
Best root_mean_squared_error score: -0.2635270170034639
Generation: 100%|██████████| 25/25 [19:52<00:00, 22.30s/it]Generation: 100%|██████████| 25/25 [19:54<00:00, 47.79s/it]
2024-09-19 23:06:48,646 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:39179' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-199f3c31ceebfff04409bf1345a44d8c', 'ndarray-fdfb9b17ac9f8c2323b4bef2176d7807'} (stimulus_id='handle-worker-cleanup-1726812408.6464405')
Fitted
Pipeline(steps=[('ardregression',
                 ARDRegression(alpha_1=5.34811e-08, alpha_2=1.70284e-08,
                               lambda_1=4.4095e-09, lambda_2=1.55419513e-05,
                               threshold_lambda=20488))])
score start
train score: {'explained_var': 0.009916383143192209, 'r2': 0.009916365146636963, 'rmse': 0.26336975431638143}
original test score: {'explained_var': 0.016403093074957464, 'r2': 0.0162358226273025, 'rmse': 0.25703228625341146}
imputed test score: {'explained_var': 0.003403743415841931, 'r2': 0.0031398534774780273, 'rmse': 0.25873745617463806}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x155384d40850>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 2 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547453cb50> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547453c7c0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474770d60> 

Generation:  1
Best root_mean_squared_error score: -0.14903550296261997
Generation:   4%|▍         | 1/25 [10:02<4:00:51, 602.13s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547457c820> 

Generation:  2
Best root_mean_squared_error score: -0.14712657330712342
Generation:   8%|▊         | 2/25 [20:05<3:51:00, 602.61s/it]Generation:  3
Best root_mean_squared_error score: -0.14712657330712342
Generation:  12%|█▏        | 3/25 [22:49<2:27:36, 402.57s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547457eec0> 

Generation:  4
Best root_mean_squared_error score: -0.14712657330712342
Generation:  16%|█▌        | 4/25 [32:53<2:48:41, 481.97s/it]Generation:  5
Best root_mean_squared_error score: -0.14601876113469442
Generation:  20%|██        | 5/25 [36:18<2:07:24, 382.24s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545e0e4070> 

Generation:  6
Best root_mean_squared_error score: -0.1453700667858176
Generation:  24%|██▍       | 6/25 [46:21<2:24:44, 457.08s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fe11720> 

Generation:  7
Best root_mean_squared_error score: -0.14341745487280333
Generation:  28%|██▊       | 7/25 [56:25<2:31:33, 505.20s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459b765c0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -0.1426411260351385
Generation:  32%|███▏      | 8/25 [1:04:46<2:22:45, 503.86s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fa283a0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  9
Best root_mean_squared_error score: -0.1426411260351385
Generation:  36%|███▌      | 9/25 [1:11:37<2:06:37, 474.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155347f654b0> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  10
Best root_mean_squared_error score: -0.1426411260351385
Generation:  40%|████      | 10/25 [1:15:46<1:41:16, 405.10s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545dc80fd0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545e105750> 

Generation:  11
Best root_mean_squared_error score: -0.1426411260351385
Generation:  44%|████▍     | 11/25 [1:25:50<1:48:43, 465.95s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554745f1f60> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -0.14238369567518505
Generation:  48%|████▊     | 12/25 [1:30:48<1:29:52, 414.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545c531480> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545e11acb0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545e12b5e0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459d8d9c0> 

Generation:  13
Best root_mean_squared_error score: -0.14238369567518505
Generation:  52%|█████▏    | 13/25 [1:40:52<1:34:26, 472.18s/it]Generation:  14
Best root_mean_squared_error score: -0.14238369567518505
Generation:  56%|█████▌    | 14/25 [1:46:01<1:17:31, 422.90s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545f0706d0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459ac68c0> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545cf20d90> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  15
Best root_mean_squared_error score: -0.14238369567518505
Generation:  60%|██████    | 15/25 [1:50:15<1:02:01, 372.17s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155459b68520> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  16
Best root_mean_squared_error score: -0.14238369567518505
Generation:  64%|██████▍   | 16/25 [1:54:51<51:27, 343.07s/it]  WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545bd18bb0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554598a2a40> 

Generation:  17
Best root_mean_squared_error score: -0.14238369567518505
Generation:  68%|██████▊   | 17/25 [2:04:56<56:13, 421.74s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545cf21450> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545988a2c0> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  18
Best root_mean_squared_error score: -0.14238369567518505
Generation:  72%|███████▏  | 18/25 [2:10:53<46:56, 402.29s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545344cbe0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  19
Best root_mean_squared_error score: -0.14183924477604173
Generation:  76%|███████▌  | 19/25 [2:17:52<40:44, 407.42s/it]Generation:  20
Best root_mean_squared_error score: -0.14183924477604173
Generation:  80%|████████  | 20/25 [2:25:30<35:13, 422.75s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545fcd0d90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  21
Best root_mean_squared_error score: -0.14159178037124975
Generation:  84%|████████▍ | 21/25 [2:31:52<27:21, 410.38s/it]Generation:  22
Best root_mean_squared_error score: -0.14159178037124975
Generation:  88%|████████▊ | 22/25 [2:38:07<19:59, 399.67s/it]Generation:  23
Best root_mean_squared_error score: -0.14159178037124975
Generation:  92%|█████████▏| 23/25 [2:41:25<11:18, 339.22s/it]Generation:  24
Best root_mean_squared_error score: -0.14159178037124975
Generation:  96%|█████████▌| 24/25 [2:45:13<05:05, 305.84s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545e066b90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545d8e2b90> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -0.14151393793083597
Generation: 100%|██████████| 25/25 [2:54:30<00:00, 381.35s/it]Generation: 100%|██████████| 25/25 [2:54:30<00:00, 418.84s/it]
2024-09-20 02:01:44,346 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:40121' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-199f3c31ceebfff04409bf1345a44d8c', 'DataFrame-161036394d196e7ecab4ff7d139aec14'} (stimulus_id='handle-worker-cleanup-1726822904.3463285')
Fitted
Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('mlpregressor',
                 MLPRegressor(alpha=4.47423644e-05, early_stopping=True,
                              hidden_layer_sizes=[493, 493, 493],
                              learning_rate='adaptive',
                              learning_rate_init=0.0005142669034,
                              n_iter_no_change=32))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.7706474638821987, 'r2': 0.7706441891730778, 'rmse': 0.1267607602853051}
test score: {'explained_var': 0.722221327504778, 'r2': 0.7221703488068738, 'rmse': 0.13659395311267708}
original test score: {'explained_var': 0.8851164281115014, 'r2': 0.8850636644601739, 'rmse': 0.0878558834900613}
score end
189
lvl
0.1
type
MCAR
num_run
1
reg_full
finished
all finished
full run takes
8.193001980317964
hours
DONE
